Ext.define('wcs.model.InterventoModel', {
    extend: 'Ext.data.Model',
    fields: [
            'codPai',
            'cntTipint',
            'codTipInt',
            'codTipIntHidden',
            'cntTipIntHidden',
            'codAnag',
            'desInt',
            'classe',
            'dataApertura',
            'esito',
            'tipo',
            'dataChiusura',
            'stato',
            'dataEsecutivita',
            'importoMensile',
            'durataMesi',
            'struttura',
            'oreSettimanali',
            'numeroPasti',
            'importo',
            'importoRettaGiornaliera',
            'giorniPresenzaMensili',
            'importoContribuzioneMensile',
            'codBeneficiario',
            'rettaMensile',
            'redditoPensione',
            'assegnoAccompagnamento',
            'importoGiornalieroISEE',
            'altriRedditi',
            'bina',
            'quoteEsclusione',
            'fasciaReddito',
            'comunitaAssistenzaFVG',
            'comunitaMBFVG',
            'comunitaAbitativaFVG',
            'impStdCosto',
            'quantita',
            'dataAvvio',
            'labelQuantita',
            'numeroDetermina',
            'protocollo',
            'flgFineDurata',
            'noteChiusura',
            'numSettimane',
            'datiOriginali',
            'codRichiedente',
            'urgente',
            'dataSospensioneRead',
            'noteSospensioneRead',
            'riduzioni',
            'approvazioneTecnica'
            

        ]
});