Ext.define('wcs.model.InterventiListModel', {
    extend: 'Ext.data.Model',
    fields: [
    'codPai',
    'desInt',
    'dataApertura',
    'dataChiusura',
    'dataEsecutivita',
    'dataAvvio',
    'importo',
    'importoErogato',
    'contribuzioniPreviste',
    'contribuzioniPagate',
    'tipo',
    'importoPrevisto',
    'cntTipint',
    'sottoposto',
    'flgRicevuta',
    'statoIntervento',
    'statoAttuale',
    'flgFineDurata',
    'codAna',
    'richiedente',
    'esito',
    'previstaProroga',
    'struttura',
    'tariffa',
	'cntTipintPadre']
});