Ext.define('wcs.model.ReferentiModel', {
    extend: 'Ext.data.Model',
    fields: [
        'nome',
        'statoCivile',
        'statoNascita',
        'statoResidenza',
        'viaResidenza',
        'viaResidenzaDes',
        'dataMorte',
        'cognome',
        'codiceFiscale',
        'comuneNascita',
        'comuneNascitaDes',
        'provinciaResidenza',
        'provinciaResidenzaDes',
        'civicoResidenza',
        'civicoResidenzaDes',
        'sesso',
        'dataNascita',
        'nazionalita',
        'cittadinanza',
        'comuneResidenza',
        'comuneResidenzaDes',
        'codAnaFamigliare',
        'codAnag',
        'qualifica',
        'codAnaComunale',
        'qualificaDes',
        'posizioneAnagrafica',
        'pai',
        'flgPai'
    ]
});