DROP TABLE IF EXISTS ANAGRAFE_FAM;
DROP TABLE IF EXISTS ANAGRAFE_SOC;
DROP TABLE IF EXISTS APPUNTAMENTO;
DROP TABLE IF EXISTS ASSOCIAZIONE;
DROP TABLE IF EXISTS BUDGET_TIP_INTERVENTO;
DROP TABLE IF EXISTS BUDGET_TIP_INTERVENTO_UOT;
DROP TABLE IF EXISTS CARTELLA_SOCIALE;
DROP TABLE IF EXISTS CODA_CSR;
DROP TABLE IF EXISTS COMUNE;
DROP TABLE IF EXISTS CONFIGURATION;
DROP TABLE IF EXISTS CONTATTO;
DROP TABLE IF EXISTS DATI_SPECIFICI;
DROP TABLE IF EXISTS DETERMINE;
DROP TABLE IF EXISTS ENTE;
DROP TABLE IF EXISTS FATTURA;
DROP TABLE IF EXISTS FATTURA_DETTAGLIO;
DROP TABLE IF EXISTS FATTURA_MESI_PRECEDENTI;
DROP TABLE IF EXISTS INDISPONIBILITA;
DROP TABLE IF EXISTS INTERVENTI_ASSOCIATI;
DROP TABLE IF EXISTS LIBERATORIA;
DROP TABLE IF EXISTS LIQUIDAZIONE;
DROP TABLE IF EXISTS LISTA_ATTESA;
DROP TABLE IF EXISTS LOG_ANAGRAFE;
DROP TABLE IF EXISTS LOG_CASSA;
DROP TABLE IF EXISTS LOG_MESSAGGI;
DROP TABLE IF EXISTS LUOGO;
DROP TABLE IF EXISTS MANDATO;
DROP TABLE IF EXISTS MANDATO_DETTAGLIO;
DROP TABLE IF EXISTS MAP_DATI_SPEC_TIPINT;
DROP TABLE IF EXISTS MAP_DATI_SPECIFICI_INTERVENTO;
DROP TABLE IF EXISTS NOTE_CONDIVISE;
DROP TABLE IF EXISTS PAI;
DROP TABLE IF EXISTS PAI_ANAGRAFICA;
DROP TABLE IF EXISTS PAI_CDG;
DROP TABLE IF EXISTS PAI_DOCUMENTO;
DROP TABLE IF EXISTS PAI_EVENTO;
DROP TABLE IF EXISTS PAI_INTERVENTO;
DROP TABLE IF EXISTS PAI_INTERVENTO_ANAGRAFICA;
DROP TABLE IF EXISTS PAI_INTERVENTO_CIV_OBB;
DROP TABLE IF EXISTS PAI_INTERVENTO_MESE;
DROP TABLE IF EXISTS PAI_MACRO_PROBLEMATICHE;
DROP TABLE IF EXISTS PAI_MICRO_PROBLEMATICHE;
DROP TABLE IF EXISTS PARAMETRI;
DROP TABLE IF EXISTS PARAMETRI_INDATA;
DROP TABLE IF EXISTS PROVINCIA;
DROP TABLE IF EXISTS RICEVUTA_CASSA;
DROP TABLE IF EXISTS STATO;
DROP TABLE IF EXISTS STRUTTURA;
DROP TABLE IF EXISTS TARIFFA;
DROP TABLE IF EXISTS TEMPLATE;
DROP TABLE IF EXISTS TIPOLOGIA_INTERVENTO;
DROP TABLE IF EXISTS TIPOLOGIA_PARAMETRI;
DROP TABLE IF EXISTS TOPONOMASTICA;
DROP TABLE IF EXISTS TOPONOMASTICA_CIVICI;
DROP TABLE IF EXISTS UNIQUE_FORM;
DROP TABLE IF EXISTS UNIQUE_TASKLIST;
DROP TABLE IF EXISTS UOT_INDIRIZZO;
DROP TABLE IF EXISTS UTENTI;
DROP TABLE IF EXISTS WS_TOKEN;


--------------------------------------------------------
--  DDL for Table ANAGRAFE_FAM
--------------------------------------------------------



  CREATE TABLE ANAGRAFE_FAM 
   (	COD_ANA BIGINT, 
	COD_ANA_FAM BIGINT, 
	COD_QUAL BIGINT, 
	 PRIMARY KEY (COD_ANA_FAM, COD_ANA));
	 
--------------------------------------------------------
--  DDL for Table ANAGRAFE_SOC
--------------------------------------------------------

  CREATE TABLE ANAGRAFE_SOC 
   (	COD_ANA BIGINT NOT NULL , 
	FLG_PERS_FG CHAR(1) NOT NULL , 
	NOME TINYTEXT DEFAULT NULL, 
	COGNOME TINYTEXT DEFAULT NULL, 
	COD_FISC CHAR(16) DEFAULT NULL, 
	PART_IVA CHAR(11) DEFAULT NULL, 
	RAG_SOC TINYTEXT DEFAULT NULL, 
	COD_ANA_COM CHAR(10) DEFAULT NULL, 
	COD_ANA_FAM_COM CHAR(10) DEFAULT NULL, 
	COD_ANA_CIVILIA CHAR(10) DEFAULT NULL, 
	DT_NASC DATETIME DEFAULT NULL, 
	FLG_SEX CHAR(1) DEFAULT NULL, 
	COD_STATO_NASC CHAR(10) DEFAULT NULL, 
	COD_PROV_ITA_NASC CHAR(10) DEFAULT NULL, 
	DES_PROV_EST_NASC TINYTEXT DEFAULT NULL, 
	COD_COM_ITA_NASC CHAR(10) DEFAULT NULL, 
	DES_COM_EST_NASC TINYTEXT DEFAULT NULL, 
	COD_STATO_CITT CHAR(10) DEFAULT NULL, 
	COD_STATO2_CITT CHAR(10) DEFAULT NULL, 
	COD_STATO_NAZ CHAR(10) DEFAULT NULL, 
	ID_PARAM_POS_ANA BIGINT DEFAULT NULL, 
	COD_STATO_RES CHAR(10) DEFAULT NULL, 
	COD_PROV_ITA_RES CHAR(10) DEFAULT NULL, 
	COD_PROV_EST_RES TINYTEXT DEFAULT NULL, 
	COD_COM_ITA_RES CHAR(10) DEFAULT NULL, 
	COD_COM_EST_RES TINYTEXT DEFAULT NULL, 
	COD_VIA_TS_RES CHAR(10) DEFAULT NULL, 
	COD_VIA_NOTS_RES TINYTEXT DEFAULT NULL, 
	COD_CIV_TS_RES CHAR(20) DEFAULT NULL, 
	COD_CIV_NOTS_RES CHAR(20) DEFAULT NULL, 
	COD_STATO_DOM CHAR(10) DEFAULT NULL, 
	COD_PROV_ITA_DOM CHAR(10) DEFAULT NULL, 
	COD_PROV_EST_DOM TINYTEXT DEFAULT NULL, 
	COD_COM_ITA_DOM CHAR(10) DEFAULT NULL, 
	COD_COM_EST_DOM TINYTEXT DEFAULT NULL, 
	COD_VIA_TS_DOM CHAR(10) DEFAULT NULL, 
	COD_VIA_NOTS_DOM TINYTEXT DEFAULT NULL, 
	COD_CIV_TS_DOM CHAR(20) DEFAULT NULL, 
	COD_CIV_NOTS_DOM CHAR(20) DEFAULT NULL, 
	NUM_TEL CHAR(20) DEFAULT NULL, 
	NUM_CELL CHAR(20) DEFAULT NULL, 
	FLG_SMS CHAR(1) NOT NULL , 
	EMAIL CHAR(200) DEFAULT NULL, 
	FLG_EMAIL CHAR(1) NOT NULL , 
	NOTE TEXT DEFAULT NULL, 
	ZONA CHAR(1) DEFAULT NULL, 
	SOTTOZONA CHAR(2) DEFAULT NULL, 
	COD_ASS CHAR(2) DEFAULT NULL, 
	DIST_SAN CHAR(1) DEFAULT NULL, 
	ENTE_GESTORE CHAR(20) DEFAULT NULL, 
	MEDICO_BASE CHAR(100) DEFAULT NULL, 
	ID_PARAM_MOD_PAGAM BIGINT, 
	IBAN_PAGAM CHAR(30) DEFAULT NULL, 
	ID_PARAM_STATO_CIV BIGINT, 
	ID_PARAM_COND_PROF BIGINT, 
	ID_PARAM_TIP_ALL BIGINT, 
	ID_PARAM_REDD BIGINT, 
	ID_PARAM_TIT BIGINT, 
	COND_FAM BIGINT, 
	ID_PARAM_STATO_FIS BIGINT, 
	REDD_MENS DECIMAL(9,2), 
	FLG_ACCOMP CHAR(1), 
	CAP_DOM CHAR(10), 
	CAP_RES CHAR(10), 
	COGNOME_CONIUGE TINYTEXT, 
	COD_SEGN_DA BIGINT, 
	DT_MORTE DATETIME, 
	PERC_INV_CIV DECIMAL(3,0), 
	DT_AGG_AB DATETIME, 
	DT_RIC_ASS_ACC DATETIME, 
	FLG_RIC_ASS_ACC CHAR(1), 
	REDDITO INT, 
	DT_UPDATE_REDDITO DATETIME, 
	ID_PARAM_TIPOLOGIA_RESIDENZA INT, 
	ATTIVITA_PRINCIPALE TINYTEXT, 
	COD_LUOGO_NASC BIGINT NOT NULL , 
	COD_LUOGO_DOM BIGINT NOT NULL , 
	COD_LUOGO_RES BIGINT NOT NULL , 
	CSR_ID TINYTEXT, 
	COD_UTE_EDUCATORE BIGINT, 
	PRESSO CHAR(40), 
	DIARIO MEDIUMTEXT, 
	CREATION_USER BIGINT, 
	CREATION_DATE DATETIME, 
	DATA_ULTIMA_RETIFICA DATETIME, 
	DATA_AGG_BATCH DATETIME DEFAULT NULL, 
	 CONSTRAINT ANAGRAFE_SOC_PK PRIMARY KEY (COD_ANA));
	 

--------------------------------------------------------
--  DDL for Table APPUNTAMENTO
--------------------------------------------------------

  CREATE TABLE APPUNTAMENTO (
    COD_AS BIGINT NOT NULL,
    COD_UTE BIGINT NOT NULL,
    COD_PAI BIGINT NOT NULL,
    TS_INI_APP DATETIME NOT NULL,
    TS_FINE_APP DATETIME NOT NULL,
    NOTE TEXT DEFAULT NULL,
    ID_APP INT NOT NULL,
    CONSTRAINT APPUNTAMENTO_PK PRIMARY KEY (ID_APP)
);
	 
--------------------------------------------------------
--  DDL for Table ASSOCIAZIONE
--------------------------------------------------------

  CREATE TABLE ASSOCIAZIONE 
   (	ID SMALLINT NOT NULL , 
	NOME TINYTEXT, 
	 CONSTRAINT ASSOCIAZIONE_PK PRIMARY KEY (ID));


	 
--------------------------------------------------------
--  DDL for Table BUDGET_TIP_INTERVENTO
--------------------------------------------------------

  CREATE TABLE BUDGET_TIP_INTERVENTO 
   (	COD_TIPINT CHAR(10) NOT NULL , 
	COD_ANNO SMALLINT NOT NULL , 
	COD_IMPE VARCHAR(255) NOT NULL , 
	COD_CONTO BIGINT NOT NULL , 
	COD_SCONTO BIGINT NOT NULL , 
	COD_CAP BIGINT NOT NULL , 
	NUM_DX BIGINT NOT NULL , 
	DT_DX DATETIME NOT NULL , 
	BDG_DISP_EUR DECIMAL(9,2) DEFAULT NULL, 
	BDG_DISP_ORE DECIMAL(9,2) DEFAULT NULL, 
	ANNO_EROGAZIONE SMALLINT DEFAULT 2024 NOT NULL , 
	 CONSTRAINT TIP_INT_IMPEGNO_PK PRIMARY KEY (COD_TIPINT, COD_ANNO, COD_IMPE));
	 
--------------------------------------------------------
--  DDL for Table BUDGET_TIP_INTERVENTO_UOT
--------------------------------------------------------

  CREATE TABLE BUDGET_TIP_INTERVENTO_UOT 
   (	COD_TIPINT CHAR(10) NOT NULL , 
	COD_ANNO SMALLINT NOT NULL , 
	COD_IMPE VARCHAR(255) NOT NULL , 
	ID_PARAM_UOT BIGINT NOT NULL , 
	BDG_DISP_EUR DECIMAL(9,2) DEFAULT NULL, 
	BDG_DISP_ORE DECIMAL(9,2) DEFAULT NULL, 
	 CONSTRAINT TIP_INT_UOT_IMPEGNO_PK PRIMARY KEY (COD_TIPINT, COD_ANNO, COD_IMPE, ID_PARAM_UOT));
	 
--------------------------------------------------------
--  DDL for Table CARTELLA_SOCIALE
--------------------------------------------------------

  CREATE TABLE CARTELLA_SOCIALE 
   (	COD_ANA BIGINT NOT NULL , 
	DES_CS TINYTEXT, 
	DT_AP_CS DATETIME, 
	DT_CH_CS DATETIME DEFAULT NULL, 
	ID_PARAM_TIP_ALL BIGINT, 
	DT_AGG_ALL DATETIME, 
	 CONSTRAINT CARTELLA_SOCIALE_PK PRIMARY KEY (COD_ANA));
	 
--------------------------------------------------------
--  DDL for Table CODA_CSR
--------------------------------------------------------

  CREATE TABLE CODA_CSR 
   (	ID_CODA BIGINT NOT NULL , 
	COD_ANA BIGINT, 
	COD_PAI BIGINT, 
	COD_TIPINT CHAR(10), 
	CNT_TIPINT SMALLINT, 
	AZIONE CHAR(30), 
	DT_INSCODA DATETIME, 
	DT_CALLCSR DATETIME, 
	DT_INSCSR DATETIME, 
	TESTO_ERRORE TEXT, 
	NUM_TENTATIVI INT, 
	DT_AVVIO DATETIME, 
	 CONSTRAINT CODA_CSR_PK PRIMARY KEY (ID_CODA));
	 
--------------------------------------------------------
--  DDL for Table COMUNE
--------------------------------------------------------

  CREATE TABLE COMUNE 
   (	COD_STATO CHAR(10) NOT NULL , 
	COD_PROV CHAR(10) NOT NULL , 
	COD_COM CHAR(10) NOT NULL , 
	DES_COM TINYTEXT NOT NULL , 
	COD_CATAST CHAR(4), 
	COD_ISTAT CHAR(15), 
	 CONSTRAINT COMUNE_PK PRIMARY KEY (COD_STATO, COD_PROV, COD_COM));
	 
--------------------------------------------------------
--  DDL for Table CONFIGURATION
--------------------------------------------------------

  CREATE TABLE CONFIGURATION 
   (	ID VARCHAR(255) NOT NULL , 
	VALUE TEXT NOT NULL , 
	DESCRIPTION TEXT, 
	 PRIMARY KEY (ID));
	 
--------------------------------------------------------
--  DDL for Table CONTATTO
--------------------------------------------------------

  CREATE TABLE CONTATTO 
   (	TS_CONT DATETIME NOT NULL , 
	COD_UTE BIGINT NOT NULL , 
	COD_ANA BIGINT NOT NULL , 
	ID_PARAM_MOTIV BIGINT NOT NULL , 
	NOTE TEXT DEFAULT NULL, 
	 CONSTRAINT CONTATTO_PK PRIMARY KEY (TS_CONT));
	 
--------------------------------------------------------
--  DDL for Table DATI_SPECIFICI
--------------------------------------------------------

  CREATE TABLE DATI_SPECIFICI 
   (	COD_CAMPO CHAR(20) NOT NULL , 
	DES_CAMPO TINYTEXT NOT NULL , 
	FLG_OBB CHAR(1) NOT NULL , 
	TIPO_CAMPO CHAR(1) NOT NULL , 
	VAL_AMM_OLD TEXT, 
	FLG_EDIT CHAR(1) NOT NULL , 
	FLG_VIS CHAR(1) NOT NULL , 
	VAL_DEF CHAR(60), 
	REG_EXPR TINYTEXT, 
	COD_CAMPO_CSR CHAR(60), 
	MSG_ERRORE TINYTEXT, 
	LUNGHEZZA SMALLINT NOT NULL , 
	DECIMALI TINYINT, 
	VAL_AMM TEXT, 
	 CONSTRAINT DATI_SPECIFICI_PK PRIMARY KEY (COD_CAMPO));
	 
--------------------------------------------------------
--  DDL for Table DETERMINE
--------------------------------------------------------

  CREATE TABLE DETERMINE 
   (	ID_DETERMINA BIGINT NOT NULL , 
	TS_DETERMINA DATETIME NOT NULL , 
	NUM_DETERMINA CHAR(10), 
	 PRIMARY KEY (ID_DETERMINA));
	 
--------------------------------------------------------
--  DDL for Table ENTE
--------------------------------------------------------

  CREATE TABLE ENTE 
   (	ID BIGINT NOT NULL , 
	NOME TINYTEXT NOT NULL , 
	DESCRIZIONE TEXT, 
	 CONSTRAINT ENTE_PK PRIMARY KEY (ID));
	 
	 
--------------------------------------------------------
--  DDL for Table FATTURA
--------------------------------------------------------

  CREATE TABLE FATTURA 
   (	COD_ANA BIGINT NOT NULL , 
	ANNO CHAR(4) NOT NULL , 
	NUM_FATT INT NOT NULL , 
	COD_PAI BIGINT NOT NULL , 
	COD_FISC CHAR(16) NOT NULL , 
	NOME TINYTEXT NOT NULL , 
	COGNOME TINYTEXT NOT NULL , 
	GRUPPO CHAR(100) DEFAULT NULL, 
	MESE_RIF BIGINT DEFAULT NULL, 
	PERIODO_DAL DATETIME DEFAULT NULL, 
	PERIODO_AL DATETIME DEFAULT NULL, 
	SCADENZA DATETIME NOT NULL , 
	CF_OBBLIGATO1 CHAR(16) DEFAULT NULL, 
	NOME_OBBL1 TINYTEXT DEFAULT NULL, 
	COGNOME_OBBL1 TINYTEXT DEFAULT NULL, 
	INDIRIZZO_OBBL1 TINYTEXT DEFAULT NULL, 
	QUOTA_OBBLIGATO1 DECIMAL(9,2) DEFAULT NULL, 
	CF_OBBLIGATO2 CHAR(16) DEFAULT NULL, 
	NOME_OBBL2 TINYTEXT DEFAULT NULL, 
	COGNOME_OBBL2 TINYTEXT DEFAULT NULL, 
	INDIRIZZO_OBBL2 TINYTEXT DEFAULT NULL, 
	QUOTA_OBBLIGATO2 DECIMAL(9,2) DEFAULT NULL, 
	CF_OBBLIGATO3 CHAR(16) DEFAULT NULL, 
	NOME_OBBL3 TINYTEXT DEFAULT NULL, 
	COGNOME_OBBL3 TINYTEXT DEFAULT NULL, 
	INDIRIZZO_OBBL3 TINYTEXT DEFAULT NULL, 
	QUOTA_OBBLIGATO3 DECIMAL(9,2) DEFAULT NULL, 
	IMPORTO_TOTALE DECIMAL(9,2) NOT NULL , 
	BOLLO DECIMAL(9,2) DEFAULT NULL, 
	ID_PARAM_FASCIA BIGINT NOT NULL , 
	ID_PARAM_STATO BIGINT NOT NULL , 
	NOTE TEXT DEFAULT NULL, 
	TIMBRO DATETIME DEFAULT current_timestamp, 
	COD_TIPINT CHAR(10) NOT NULL , 
	CNT_TIPINT SMALLINT NOT NULL , 
	CAUSALE TEXT, 
	RISCOSSO DECIMAL(9,2), 
	ID_FATT BIGINT, 
	ID_PARAM_PAGAM BIGINT, 
	IMP_IVA DECIMAL(9,2), 
	ID_PARAM_IVA BIGINT, 
	CONTRIBUTO DECIMAL(9,2), 
	 CONSTRAINT FATTURA_PK PRIMARY KEY (ID_FATT));
	 
	 
--------------------------------------------------------
--  DDL for Table FATTURA_DETTAGLIO
--------------------------------------------------------

  CREATE TABLE FATTURA_DETTAGLIO 
   (	ANNO_EFF SMALLINT NOT NULL , 
	ID_FATT BIGINT NOT NULL , 
	MESE_EFF TINYINT NOT NULL , 
	COD_TIPINT CHAR(10) NOT NULL , 
	ID_PARAM_UNITA_MISURA BIGINT NOT NULL , 
	QT_INPUTATA DECIMAL(9,2) NOT NULL , 
	IMPORTO DECIMAL(9,2) NOT NULL , 
	AUMENTO DECIMAL(9,2) DEFAULT NULL, 
	RIDUZIONE DECIMAL(9,2) DEFAULT NULL, 
	TIMBRO DATETIME DEFAULT current_timestamp, 
	ID_FATT_DETTAGLIO BIGINT NOT NULL , 
	VAR_STRAORD DECIMAL(9,2), 
	CAUS_VAR CHAR(60), 
	 CONSTRAINT FATTURA_DETTAGLIO_PK PRIMARY KEY (ID_FATT_DETTAGLIO));
	 
	 
	 
--------------------------------------------------------
--  DDL for Table FATTURA_MESI_PRECEDENTI
--------------------------------------------------------

  CREATE TABLE FATTURA_MESI_PRECEDENTI 
   (	ID_FATT_PRINC BIGINT, 
	ID_FATT_CORR BIGINT, 
	 PRIMARY KEY (ID_FATT_PRINC, ID_FATT_CORR));
	 
--------------------------------------------------------
--  DDL for Table INDISPONIBILITA
--------------------------------------------------------

  CREATE TABLE INDISPONIBILITA 
   (	COD_AS BIGINT NOT NULL , 
	TS_INI_APP DATETIME NOT NULL , 
	TS_FINE_APP DATETIME NOT NULL , 
	ID_IND INT NOT NULL , 
	 CONSTRAINT INDISPONIBILITA_PK PRIMARY KEY (ID_IND));
	 
--------------------------------------------------------
--  DDL for Table INTERVENTI_ASSOCIATI
--------------------------------------------------------

  CREATE TABLE INTERVENTI_ASSOCIATI 
   (	ID INT NOT NULL , 
	COD_PAI BIGINT, 
	COD_PAI1 BIGINT, 
	COD_TIPINT1 CHAR(10), 
	CNT_TIPINT1 SMALLINT, 
	COD_TIPINT CHAR(10), 
	CNT_TIPINT SMALLINT, 
	TIPO_LEGAME TINYTEXT, 
	 CONSTRAINT INTERVENTI_ASSOCIATI_PK PRIMARY KEY (ID));
	 
--------------------------------------------------------
--  DDL for Table LIBERATORIA
--------------------------------------------------------

  CREATE TABLE LIBERATORIA 
   (ID BIGINT NOT NULL , 
	COD_ANA BIGINT NOT NULL , 
	ID_ASSOCIAZIONE SMALLINT, 
	COD_UTE BIGINT, 
	DT_FIRMA DATETIME, 
	CONSTRAINT LIBERATORIA_PK PRIMARY KEY (ID));
	 
	 
--------------------------------------------------------
--  DDL for Table LIQUIDAZIONE
--------------------------------------------------------
  CREATE TABLE LIQUIDAZIONE 
   (	ID_PROG BIGINT NOT NULL , 
	COD_TIPINT CHAR(10) NOT NULL , 
	CNT_TIPINT SMALLINT NOT NULL , 
	MESE_RIF SMALLINT DEFAULT NULL, 
	PERIODO_DAL DATETIME DEFAULT NULL, 
	PERIODO_AL DATETIME DEFAULT NULL, 
	NOTE TEXT DEFAULT NULL, 
	TIMBRO DATETIME DEFAULT current_timestamp, 
	 CONSTRAINT LIQUIDAZIONE_PK PRIMARY KEY (ID_PROG));

	 
--------------------------------------------------------
--  DDL for Table LISTA_ATTESA
--------------------------------------------------------

  CREATE TABLE LISTA_ATTESA 
   (	COD_LISTA_ATT BIGINT NOT NULL , 
	DES_LISTA_ATT TINYTEXT NOT NULL , 
	FLG_TIPINT CHAR(1) NOT NULL , 
	FLG_COG CHAR(1) NOT NULL , 
	FLG_NOM CHAR(1) NOT NULL , 
	FLG_COD_FISC CHAR(1) NOT NULL , 
	FLG_ISEE CHAR(1) NOT NULL , 
	FLG_DT_NASC CHAR(1) NOT NULL , 
	FLG_DT_DOM CHAR(1) NOT NULL , 
	FLG_BINA CHAR(1) NOT NULL , 
	FLG_AS CHAR(1) NOT NULL , 
	FLG_UOT CHAR(1) NOT NULL , 
	FLG_DIST_SAN CHAR(1) NOT NULL , 
	FLG_REF CHAR(1) NOT NULL , 
	FLG_NUM_FIGLI CHAR(1) NOT NULL , 
	 CONSTRAINT LISTA_ATTESA_PK PRIMARY KEY (COD_LISTA_ATT));


--------------------------------------------------------
--  DDL for Table LOG_ANAGRAFE
--------------------------------------------------------

  CREATE TABLE LOG_ANAGRAFE 
   (	TS_EVE DATETIME NOT NULL, 
	COD_UTE BIGINT NOT NULL, 
	COD_PAI BIGINT, 
	COD_ANA BIGINT NOT NULL, 
	 CONSTRAINT LOG_ANAGRAFE_PK PRIMARY KEY (TS_EVE));
	 
--------------------------------------------------------
--  DDL for Table LOG_CASSA
--------------------------------------------------------

  CREATE TABLE LOG_CASSA 
   (	ID INT NOT NULL, 
	TIPO_OPERAZIONE TINYTEXT, 
	PARAMETRI TINYTEXT, 
	IMPORTO DECIMAL(9,2), 
	IMPORTO_TOTALE DECIMAL(9,2), 
	DATA_OPERAZIONE DATETIME, 
	COD_PAI BIGINT, 
	CNT_TIPINT SMALLINT, 
	 CONSTRAINT LOG_CASA_PK PRIMARY KEY (ID));
	 
--------------------------------------------------------
--  DDL for Table LOG_MESSAGGI
--------------------------------------------------------

  CREATE TABLE LOG_MESSAGGI 
   (	TS_ERR DATETIME NOT NULL, 
	COD_PAI BIGINT NOT NULL, 
	COD_TIPINT CHAR(10) NOT NULL, 
	CNT_TIPINT SMALLINT NOT NULL, 
	DES_ERR TINYTEXT NOT NULL, 
	FLG_TIPO_ERR CHAR(1) NOT NULL, 
	COD_ERR TINYTEXT NOT NULL, 
	 CONSTRAINT LOG_MESSAGGIO_PK PRIMARY KEY (TS_ERR));
	 
--------------------------------------------------------
--  DDL for Table LUOGO
--------------------------------------------------------

  CREATE TABLE LUOGO 
   (	COD_LUOGO BIGINT NOT NULL, 
	COD_STATO CHAR(10) DEFAULT NULL, 
	COD_PROV CHAR(10) DEFAULT NULL, 
	COD_COM CHAR(10) DEFAULT NULL, 
	COD_VIA CHAR(20) DEFAULT NULL, 
	COD_CIV CHAR(20) DEFAULT NULL, 
	DES_PROV TINYTEXT DEFAULT NULL, 
	DES_COM TINYTEXT DEFAULT NULL, 
	DES_VIA TINYTEXT DEFAULT NULL, 
	DES_CIV TINYTEXT DEFAULT NULL, 
	CAP TINYTEXT DEFAULT NULL, 
	 CONSTRAINT LUOGO_PK PRIMARY KEY (COD_LUOGO));
	 
--------------------------------------------------------
--  DDL for Table MANDATO
--------------------------------------------------------

  CREATE TABLE MANDATO 
   (	COD_PAI BIGINT NOT NULL, 
	COD_ANA_BENEFICIARIO BIGINT NOT NULL, 
	NUMERO_MANDATO BIGINT, 
	ANNO_DECR SMALLINT NOT NULL, 
	CAPITOLO_DECR BIGINT NOT NULL, 
	NUM_DECR BIGINT NOT NULL, 
	DATA_DECR DATETIME NOT NULL, 
	COGNOME_BENEFICIARIO TEXT NOT NULL, 
	NOME_BENEFICIARIO TEXT NOT NULL, 
	CF_BENEFICIARIO CHAR(16) NOT NULL, 
	INDIRIZZO TEXT NOT NULL, 
	GRUPPO TINYTEXT NOT NULL, 
	MESE_RIF SMALLINT NOT NULL, 
	PERIODO_DAL DATETIME DEFAULT NULL, 
	PERIODO_AL DATETIME DEFAULT NULL, 
	ID_PARAM_FASCIA BIGINT NOT NULL, 
	COD_ANA_DELEGANTE BIGINT, 
	CF_DELEGANTE CHAR(16) NOT NULL, 
	COGNOME_DELEGANTE TEXT DEFAULT NULL, 
	NOME_DELEGANTE TEXT DEFAULT NULL, 
	MODALITA_EROGAZIONE TINYTEXT DEFAULT NULL, 
	IBAN CHAR(30) DEFAULT NULL, 
	IMPORTO DECIMAL(9,2) NOT NULL, 
	ID_PARAM_STATO BIGINT NOT NULL, 
	TIMBRO DATETIME DEFAULT current_timestamp, 
	COD_TIPINT CHAR(10) NOT NULL, 
	CNT_TIPINT SMALLINT NOT NULL, 
	ID_MAN BIGINT, 
	NOTE TEXT, 
	 CONSTRAINT MANDATO_PK PRIMARY KEY (ID_MAN));
	 
--------------------------------------------------------
--  DDL for Table MANDATO_DETTAGLIO
--------------------------------------------------------

  CREATE TABLE MANDATO_DETTAGLIO 
   (	COD_PAI BIGINT NOT NULL, 
	NUMERO_MANDATO BIGINT, 
	MESE_EFF TINYINT NOT NULL, 
	COD_TIPINT CHAR(10) NOT NULL, 
	CNT_TIPINT SMALLINT NOT NULL, 
	ID_PARAM_UNITA_MISURA BIGINT NOT NULL, 
	QT_ASSEGNATA DECIMAL(9,2) NOT NULL, 
	COSTO_UNITARIO DECIMAL(9,2) NOT NULL, 
	COSTO_TOTALE DECIMAL(9,2) NOT NULL, 
	AUMENTO DECIMAL(9,2) DEFAULT NULL, 
	RIDUZIONE DECIMAL(9,2) DEFAULT NULL, 
	TIMBRO DATETIME DEFAULT current_timestamp, 
	ID_MAN_DETTAGLIO BIGINT NOT NULL, 
	ID_MAN BIGINT, 
	 CONSTRAINT MANDATO_DETAGLIO_PK PRIMARY KEY (ID_MAN_DETTAGLIO));
	 
	 
--------------------------------------------------------
--  DDL for Table MAP_DATI_SPEC_TIPINT
--------------------------------------------------------

  CREATE TABLE MAP_DATI_SPEC_TIPINT 
   (	COD_TIPINT CHAR(10) NOT NULL, 
	COD_CAMPO CHAR(20) NOT NULL, 
	ROW_CAMPO TINYINT NOT NULL, 
	COL_CAMPO TINYINT NOT NULL, 
	 CHECK (COD_TIPINT IS NOT NULL), 
	 CHECK (COD_CAMPO IS NOT NULL), 
	 CHECK (ROW_CAMPO IS NOT NULL), 
	 CHECK (COL_CAMPO IS NOT NULL), 
	 PRIMARY KEY (COD_TIPINT, COD_CAMPO)
	 );
	 
--------------------------------------------------------
--  DDL for Table MAP_DATI_SPECIFICI_INTERVENTO
--------------------------------------------------------

  CREATE TABLE MAP_DATI_SPECIFICI_INTERVENTO 
   (	COD_PAI BIGINT NOT NULL, 
	COD_TIPINT CHAR(10) NOT NULL, 
	CNT_TIPINT SMALLINT NOT NULL, 
	COD_CAMPO CHAR(20) NOT NULL, 
	COD_VAL_CAMPO CHAR(20), 
	VAL_CAMPO TEXT NOT NULL, 
	 PRIMARY KEY (COD_PAI, COD_TIPINT, CNT_TIPINT, COD_CAMPO)
	 );
	 

--------------------------------------------------------
--  DDL for Table NOTE_CONDIVISE
--------------------------------------------------------

  CREATE TABLE NOTE_CONDIVISE 
   (	ID INT NOT NULL, 
	DATA_INSERIMENTO DATETIME, 
	COD_ANA BIGINT NOT NULL, 
	COD_UTE BIGINT NOT NULL, 
	TITOLO CHAR(40), 
	ESTESO TEXT
	);
	
--------------------------------------------------------
--  DDL for Table PAI
--------------------------------------------------------

  CREATE TABLE PAI 
   (	COD_PAI BIGINT NOT NULL, 
	COD_ANA BIGINT NOT NULL, 
	DT_APE_PAI DATETIME NOT NULL, 
	FLG_STATO_PAI CHAR(1) NOT NULL, 
	FLG_CSR CHAR(1), 
	DT_INVIO_CSR DATETIME DEFAULT NULL, 
	FLG_MOD_CSR CHAR(1), 
	DT_CHIUS_PAI DATETIME DEFAULT NULL, 
	MOTIV_CHIUS TINYTEXT DEFAULT NULL, 
	NUM_PG CHAR(10) DEFAULT NULL, 
	DT_PG DATETIME DEFAULT NULL, 
	NUM_NUC SMALLINT DEFAULT NULL, 
	NUM_FIGLI SMALLINT DEFAULT NULL, 
	NUM_FIGLI_CONV SMALLINT DEFAULT NULL, 
	PROVV_GIUDIZ TINYTEXT DEFAULT NULL, 
	NOTE_COND_FAM TEXT DEFAULT NULL, 
	FLG_AGE_SAN CHAR(1), 
	FLG_CAR_SA CHAR(1), 
	FLG_CAR_SS CHAR(1), 
	FLG_CAR_VOL CHAR(1), 
	FLG_CAR_PARR CHAR(1), 
	FLG_CAR_ALTRO CHAR(1), 
	CAR_ALTRO CHAR(100) DEFAULT NULL, 
	ID_PARAM_DIAG_SOC BIGINT DEFAULT NULL, 
	NOTE_DIAG_SOC TEXT DEFAULT NULL, 
	OBIETTIVI TINYTEXT DEFAULT NULL, 
	ID_PARAM_UOT BIGINT DEFAULT NULL, 
	COD_UTE_AS BIGINT, 
	DT_DIAG DATETIME, 
	MOTIV TINYTEXT, 
	ISEE DECIMAL(9,2), 
	DT_SCAD_ISEE DATETIME, 
	ID_PARAM_FASCIA BIGINT DEFAULT 344 NOT NULL, 
	FLG_DEMENZA CHAR(1), 
	ADL SMALLINT, 
	HABITAT CHAR(1), 
	ID_PARAM_CERTIFICATO_L104 BIGINT, 
	ID_PARAM_PROVV_GIUDIZIARIO BIGINT, 
	DT_CAMBIO_FASCIA DATETIME, 
	ISEE2 DECIMAL(9,2), 
	ISEE3 DECIMAL(9,2), 
	 CONSTRAINT PAI_PK PRIMARY KEY (COD_PAI)
	 );
--------------------------------------------------------
--  DDL for Table PAI_ANAGRAFICA
--------------------------------------------------------

  CREATE TABLE PAI_ANAGRAFICA 
   (	COD_PAI BIGINT NOT NULL, 
	COD_ANA_SOC BIGINT NOT NULL, 
	ID_PARAM_QUAL_ANA_SOC BIGINT, 
	 CONSTRAINT PAI_ANAGRAFICA_PK PRIMARY KEY (COD_PAI, COD_ANA_SOC)
	 );
--------------------------------------------------------
--  DDL for Table PAI_CDG
--------------------------------------------------------

  CREATE TABLE PAI_CDG 
   (	COD_PAI BIGINT NOT NULL, 
	COD_TIPINT CHAR(10) NOT NULL, 
	CNT_TIPINT SMALLINT NOT NULL, 
	TS_EVE_CFG DATETIME DEFAULT current_timestamp, 
	QTA_PREV DECIMAL(9,2) NOT NULL, 
	QTA_EROG DECIMAL(9,2) NOT NULL, 
	IMP_STD DECIMAL(9,2) NOT NULL, 
	IMP_COMPL DECIMAL(9,2) NOT NULL, 
	COD_ANNO SMALLINT NOT NULL, 
	COD_CAP BIGINT NOT NULL, 
	COD_IMPE VARCHAR(255) NOT NULL, 
	CCELE CHAR(10) NOT NULL, 
	ANNO_EFF SMALLINT NOT NULL, 
	MESE_EFF TINYINT NOT NULL, 
	IMP_VAR DECIMAL(9,2), 
	COD_ANA BIGINT, 
	 CONSTRAINT PAI_CDG_PK PRIMARY KEY (COD_PAI, COD_TIPINT, CNT_TIPINT, MESE_EFF, ANNO_EFF, COD_ANNO, COD_IMPE));
	 
--------------------------------------------------------
--  DDL for Table PAI_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE PAI_DOCUMENTO 
   (	ID_DOCUMENTO BIGINT NOT NULL, 
	COD_TIPDOC CHAR(25) NOT NULL, 
	VER INT NOT NULL, 
	DT_DOC DATETIME NOT NULL, 
	BLOB_DOC BLOB NOT NULL, 
	COD_PAI BIGINT, 
	COD_TIPINT CHAR(10), 
	CNT_TIPINT SMALLINT, 
	NOME_FILE TINYTEXT NOT NULL, 
	COD_UTE_AUT BIGINT NOT NULL, 
	NUM_PROT CHAR(20), 
	DT_PROT DATETIME, 
	TIPO_DETERMINA CHAR(50), 
	 PRIMARY KEY (ID_DOCUMENTO));
	 
	 
--------------------------------------------------------
--  DDL for Table PAI_EVENTO
--------------------------------------------------------

  CREATE TABLE PAI_EVENTO 
   (	COD_PAI BIGINT NOT NULL, 
	COD_TIPINT CHAR(10), 
	CNT_TIPINT SMALLINT, 
	TS_EVE_PAI DATETIME DEFAULT current_timestamp NOT NULL, 
	COD_UTE BIGINT NOT NULL, 
	PAI_DOX BLOB NOT NULL, 
	BRE_DOX BLOB DEFAULT NULL, 
	DES_EVENTO TEXT, 
	FLG_DX_STAMPA CHAR(1) DEFAULT 'N' NOT NULL, 
	ID_DETERMINA BIGINT, 
	ID_EVENTO BIGINT, 
	COD_TMPL BIGINT, 
	 CONSTRAINT PAI_EVENTO_PK PRIMARY KEY (ID_EVENTO));
	 
	 
--------------------------------------------------------
--  DDL for Table PAI_INTERVENTO
--------------------------------------------------------

  CREATE TABLE PAI_INTERVENTO 
   (	COD_PAI BIGINT NOT NULL, 
	COD_TIPINT CHAR(10) NOT NULL, 
	CNT_TIPINT SMALLINT NOT NULL, 
	STATO_INT CHAR(1) NOT NULL, 
	DT_ESEC DATETIME DEFAULT NULL, 
	DT_CHIUS DATETIME DEFAULT NULL, 
	IND_ESITO_INT CHAR(2) DEFAULT NULL, 
	NOTE_CHIUS TEXT DEFAULT NULL, 
	COSTO_PREV DECIMAL(9,2) DEFAULT NULL, 
	DT_APE DATETIME, 
	CLASSE_INT BIGINT, 
	DUR_MESI TINYINT, 
	DT_AVVIO DATETIME, 
	QUANTITA INT, 
	DS_COD_ANA_BENEF BIGINT, 
	DS_ID_PARAM_FASCIA_REDD BIGINT, 
	DT_FINE DATETIME, 
	NUM_DETERMINA CHAR(60), 
	IBAN_DELEGATO TINYTEXT, 
	DT_RICH_APP DATETIME, 
	CSR_ID TINYTEXT, 
	MOTIVAZIONE TEXT, 
	DT_FINE_INDIC DATETIME, 
	DT_AVVIO_PROP DATETIME, 
	PROTOCOLLO CHAR(200), 
	DUR_SETTIMANE BIGINT, 
	DATI_ORIGINALI TEXT, 
	STATO_ATTUALE CHAR(200), 
	DS_COD_ANA_RICHIEDENTE BIGINT, 
	RINNOVATO INT DEFAULT 1 NOT NULL, 
	MESI_PROROGA BIGINT, 
	COD_IMP_PROROGA CHAR(200), 
	DT_FINE_PROROGA DATETIME, 
	URGENTE CHAR(1) DEFAULT 'N' NOT NULL, 
	DT_SOSP DATETIME DEFAULT NULL, 
	NOTE_SOSPENSIONE TEXT DEFAULT NULL, 
	APPROVAZIONE_TECNICA CHAR(1) DEFAULT 'N' NOT NULL, 
	ID_ASSOCIAZIONE SMALLINT DEFAULT 1, 
	ID_TARIFFA BIGINT, 
	TESTO_AUTORIZZAZIONE TEXT, 
	UTENTE_CREAZIONE_RECORD CHAR(100), 
	DATA_CREAZIONE_RECORD DATETIME, 
	 CONSTRAINT PAI_INTERVENTO_PK PRIMARY KEY (COD_PAI, COD_TIPINT, CNT_TIPINT));
	 
--------------------------------------------------------
--  DDL for Table PAI_INTERVENTO_ANAGRAFICA
--------------------------------------------------------

  CREATE TABLE PAI_INTERVENTO_ANAGRAFICA 
   (	COD_PAI BIGINT NOT NULL, 
	COD_TIPINT CHAR(10) NOT NULL, 
	CNT_TIPINT SMALLINT NOT NULL, 
	COD_ANA_SOC BIGINT NOT NULL, 
	ID_PARAM_QUAL_ANA_SOC BIGINT NOT NULL, 
	 CONSTRAINT PAI_INT_ANAGRAFICA_PK PRIMARY KEY (COD_PAI, COD_TIPINT, CNT_TIPINT, COD_ANA_SOC, ID_PARAM_QUAL_ANA_SOC));
	 
	 
	 
--------------------------------------------------------
--  DDL for Table PAI_INTERVENTO_CIV_OBB
--------------------------------------------------------

  CREATE TABLE PAI_INTERVENTO_CIV_OBB 
   (	COD_PAI BIGINT NOT NULL, 
	COD_TIPINT CHAR(10) NOT NULL, 
	CNT_TIPINT SMALLINT NOT NULL, 
	COD_ANA_CO BIGINT NOT NULL, 
	IMP_CO DECIMAL(9,2) NOT NULL, 
	 CONSTRAINT PAI_INTERVENTO_CIV_OBB_PK PRIMARY KEY (COD_PAI, COD_TIPINT, CNT_TIPINT, COD_ANA_CO));
	 
	 
	
--------------------------------------------------------
--  DDL for Table PAI_INTERVENTO_MESE
--------------------------------------------------------

  CREATE TABLE PAI_INTERVENTO_MESE 
   (	COD_PAI BIGINT NOT NULL, 
	COD_TIPINT CHAR(10) NOT NULL, 
	CNT_TIPINT SMALLINT NOT NULL, 
	ANNO_EFF SMALLINT NOT NULL, 
	MESE_EFF TINYINT NOT NULL, 
	ANNO SMALLINT NOT NULL, 
	COD_IMP VARCHAR(255) NOT NULL, 
	BDG_PREV_EUR DECIMAL(9,2) NOT NULL, 
	BDG_PREV_QTA DECIMAL(9,2), 
	BDG_CONS_EUR DECIMAL(9,2), 
	BDG_CONS_QTA DECIMAL(9,2), 
	ID_FATT_DETTAGLIO BIGINT, 
	BDG_CONS_QTA_BENEF DECIMAL(9,2), 
	BDG_CONS_VAR DECIMAL(9,2), 
	CAUS_VAR CHAR(60), 
	NOTE TEXT, 
	FLG_PROP CHAR(1) DEFAULT 'S' NOT NULL, 
	ID_MAN_DETTAGLIO BIGINT, 
	GG_ASSENZA SMALLINT, 
	IMP_VAR DECIMAL(9,2), 
	MOTIVAZIONE_VARIAZIONE_SPESA INT, 
	ID_PARAM_FASCIA BIGINT, 
	ACQUISITO TINYINT DEFAULT 1 NOT NULL, 
	BDG_CONS_RIENTR DECIMAL(9,2), 
	COD_IMP_PROROGA TINYTEXT, 
	 CONSTRAINT PAI_INTERVENTO_MESE_PK PRIMARY KEY (COD_PAI, COD_TIPINT, CNT_TIPINT, ANNO_EFF, MESE_EFF, ANNO, COD_IMP));
	 
	 
--------------------------------------------------------
--  DDL for Table PAI_MACRO_PROBLEMATICHE
--------------------------------------------------------

  CREATE TABLE PAI_MACRO_PROBLEMATICHE 
   (	COD_PAI BIGINT, 
	IP_MACRO_PROBLEMATICA BIGINT, 
	IP_RILEVANZA BIGINT, 
	IP_FRONTEGGIAMENTO BIGINT, 
	IP_OBIETTIVO_PREVALENTE BIGINT, 
	DETTAGLIO_NOTE TEXT, 
	 CONSTRAINT PAI_MACRO_PROBLEMATICHE_PK PRIMARY KEY (COD_PAI, IP_MACRO_PROBLEMATICA));
	 
	 
--------------------------------------------------------
--  DDL for Table PAI_MICRO_PROBLEMATICHE
--------------------------------------------------------

  CREATE TABLE PAI_MICRO_PROBLEMATICHE 
   (	COD_PAI BIGINT, 
	IP_MACRO_PROBLEMATICA BIGINT, 
	IP_MICRO_PROBLEMATICA BIGINT, 
	 CONSTRAINT PAI_MICRO_PROBLEMATICHE_PK PRIMARY KEY (COD_PAI, IP_MACRO_PROBLEMATICA, IP_MICRO_PROBLEMATICA));
	 
	 
--------------------------------------------------------
--  DDL for Table PARAMETRI
--------------------------------------------------------

  CREATE TABLE PARAMETRI 
   (	ID_PARAM BIGINT NOT NULL, 
	TIP_PARAM CHAR(10) NOT NULL, 
	COD_PARAM CHAR(10) NOT NULL, 
	FLG_ATTIVO CHAR(1) NOT NULL, 
	 CONSTRAINT PARAMETRI_PK PRIMARY KEY (ID_PARAM));
	 
	 
--------------------------------------------------------
--  DDL for Table PARAMETRI_INDATA
--------------------------------------------------------

  CREATE TABLE PARAMETRI_INDATA 
   (	ID_PARAM_INDATA BIGINT NOT NULL, 
	ID_PARAM BIGINT NOT NULL, 
	DT_INI_VAL DATETIME DEFAULT current_timestamp NOT NULL, 
	DES_PARAM TINYTEXT NOT NULL, 
	DATE_PARAM DATETIME DEFAULT current_timestamp, 
	DECIMAL_PARAM DECIMAL(16,6) DEFAULT NULL, 
	TXT1_PARAM CHAR(80) DEFAULT NULL, 
	TXT2_PARAM CHAR(30) DEFAULT NULL, 
	TXT3_PARAM CHAR(30) DEFAULT NULL, 
	TXT4_PARAM CHAR(30) DEFAULT NULL, 
	TXT5_PARAM CHAR(30) DEFAULT NULL, 
	TXT6_PARAM CHAR(30) DEFAULT NULL, 
	TXT7_PARAM CHAR(30) DEFAULT NULL, 
	TXT8_PARAM CHAR(30) DEFAULT NULL, 
	PIATTAFORMA CHAR(15), 
	 PRIMARY KEY (ID_PARAM_INDATA));
	 
	 
--------------------------------------------------------
--  DDL for Table PROVINCIA
--------------------------------------------------------

  CREATE TABLE PROVINCIA 
   (	COD_STATO CHAR(10) NOT NULL, 
	COD_PROV CHAR(10) NOT NULL, 
	DES_PROV TINYTEXT NOT NULL, 
	 CONSTRAINT PROVINCIA_PK PRIMARY KEY (COD_STATO, COD_PROV));
	 
	 
--------------------------------------------------------
--  DDL for Table RICEVUTA_CASSA
--------------------------------------------------------

  CREATE TABLE RICEVUTA_CASSA 
   (	COD_PAI BIGINT NOT NULL, 
	NUMERO_RICEVUTA INT DEFAULT 0 NOT NULL, 
	UTENTE TINYTEXT NOT NULL, 
	IMPORTO DECIMAL(9,2) NOT NULL, 
	DATA_EMISSIONE DATETIME, 
	CNT_TIPINT SMALLINT NOT NULL, 
	 CONSTRAINT RICEVUTA_CASSA_PK PRIMARY KEY (COD_PAI, CNT_TIPINT));
	 
	 
--------------------------------------------------------
--  DDL for Table STATO
--------------------------------------------------------

  CREATE TABLE STATO 
   (	COD_STATO CHAR(10) NOT NULL, 
	DES_STATO TINYTEXT NOT NULL, 
	COD_GRUPPO CHAR(20), 
	COD_CATAST CHAR(20), 
	COD_ISTAT CHAR(15), 
	COD_CITT_INSIEL CHAR(20), 
	COD_ISO_3166_1 CHAR(20), 
	 CONSTRAINT STATO_PK PRIMARY KEY (COD_STATO));
 
--------------------------------------------------------
--  DDL for Table STRUTTURA
--------------------------------------------------------

  CREATE TABLE STRUTTURA 
   (	ID BIGINT NOT NULL, 
	NOME TINYTEXT, 
	INDIRIZZO TINYTEXT, 
	COD_TIPINT CHAR(10), 
	CSR_ID CHAR(40), 
	ID_ENTE BIGINT, 
	 CONSTRAINT STRUTTURA_PK PRIMARY KEY (ID));
	 
	 
--------------------------------------------------------
--  DDL for Table TARIFFA
--------------------------------------------------------

  CREATE TABLE TARIFFA 
   (	ID BIGINT NOT NULL, 
	ID_STRUTTURA BIGINT NOT NULL, 
	ANNO SMALLINT NOT NULL, 
	COSTO DECIMAL(9,2) NOT NULL, 
	DESCRIZIONE TEXT, 
	FORFAIT CHAR(1) DEFAULT 'N' NOT NULL, 
	 CONSTRAINT TARIFFA_PK PRIMARY KEY (ID)
	 );
	 

--------------------------------------------------------
--  DDL for Table TEMPLATE
--------------------------------------------------------

  CREATE TABLE TEMPLATE 
   (	COD_TMPL BIGINT NOT NULL, 
	DES_TMPL TINYTEXT NOT NULL, 
	NOME_FILE TINYTEXT DEFAULT NULL, 
	CLOB_TMPL BLOB NOT NULL, 
	 CONSTRAINT TEMPLATE_PK PRIMARY KEY (COD_TMPL));
	 
	 
--------------------------------------------------------
--  DDL for Table TIPOLOGIA_INTERVENTO
--------------------------------------------------------

  CREATE TABLE TIPOLOGIA_INTERVENTO 
   (	COD_TIPINT CHAR(10) NOT NULL, 
	DES_TIPINT TINYTEXT NOT NULL, 
	FLG_PAI CHAR(1) NOT NULL, 
	ID_PARAM_CLASSE_TIPINT BIGINT NOT NULL, 
	CCELE CHAR(10) NOT NULL, 
	IMP_STD_COSTO DECIMAL(9,2) DEFAULT 0 NOT NULL, 
	COD_LISTA_ATT BIGINT DEFAULT NULL, 
	ID_PARAM_STRUTTURA BIGINT, 
	COD_PROC_FO CHAR(10) DEFAULT NULL, 
	COD_PROC_ESE CHAR(10) DEFAULT NULL, 
	COD_PROC_GEST CHAR(10) DEFAULT NULL, 
	COD_TMPL_ESE BIGINT NOT NULL, 
	COD_TMPL_VAR BIGINT NOT NULL, 
	COD_TMPL_CHIUS BIGINT NOT NULL, 
	ID_PARAM_SRV BIGINT NOT NULL, 
	FLG_FATT CHAR(1) NOT NULL, 
	FLG_PAGAM CHAR(1) NOT NULL, 
	COD_INT_CSR CHAR(20), 
	COD_TMPL_COMLIQ BIGINT, 
	COD_TIPINT_CSR CHAR(10), 
	COD_TMPL_LETT_PAG BIGINT, 
	IMP_STD_ENTR DECIMAL(9,2) DEFAULT 0 NOT NULL, 
	IMP_STD_SPESA DECIMAL(9,2) DEFAULT 0 NOT NULL, 
	ID_PARAM_GRUTE BIGINT, 
	COD_TMPL_ESE_MUL BIGINT NOT NULL, 
	COD_TMPL_VAR_MUL BIGINT NOT NULL, 
	COD_TMPL_CHIUS_MUL BIGINT NOT NULL, 
	FLG_RDBFAP CHAR(1), 
	FLG_ATTIVO CHAR(1) NOT NULL, 
	ID_PARAM_UNI_MIS BIGINT, 
	FLG_VIS CHAR(1) NOT NULL, 
	FLG_FINE_DURATA CHAR(1) DEFAULT 'D' NOT NULL, 
	FLG_RICEVUTA CHAR(1) DEFAULT 'N' NOT NULL, 
	COD_TMPL_RICEVUTA BIGINT, 
	CONTATORE_RICEVUTA INT DEFAULT 1 NOT NULL, 
	FLG_RINNOVO_AUTO CHAR(1) DEFAULT 'N' NOT NULL, 
	RESP_PROC TINYTEXT, 
	UFF_RIF TINYTEXT, 
	IP_ALIQUOTA_IVA BIGINT, 
	FLG_RINNOVO CHAR(1) DEFAULT 'N' NOT NULL, 
	FLG_APP_TEC CHAR(1) DEFAULT 'N' NOT NULL, 
	COD_TMPL_DOC_AUTORIZZAZIONE BIGINT, 
	FLG_DOC_AUTORIZZAZIONE CHAR(1), 
	 CONSTRAINT TIPOLOGIA_INTERVENTO_PK PRIMARY KEY (COD_TIPINT));
	 
	 
--------------------------------------------------------
--  DDL for Table TIPOLOGIA_PARAMETRI
--------------------------------------------------------

  CREATE TABLE TIPOLOGIA_PARAMETRI 
   (	TIP_PARAM CHAR(10), 
	DES_TIP_PARAM TINYTEXT NOT NULL, 
	FLG_INDATA CHAR(1) DEFAULT 'N' NOT NULL, 
	 PRIMARY KEY (TIP_PARAM));
	 
	 
--------------------------------------------------------
--  DDL for Table TOPONOMASTICA
--------------------------------------------------------

  CREATE TABLE TOPONOMASTICA 
   (	COD_STATO CHAR(10) NOT NULL, 
	COD_PROV CHAR(10) NOT NULL, 
	COD_COM CHAR(10) NOT NULL, 
	COD_VIA CHAR(20) NOT NULL, 
	DES_VIA TINYTEXT NOT NULL, 
	 CONSTRAINT TOPONOMASTICA_PK PRIMARY KEY (COD_STATO, COD_PROV, COD_COM, COD_VIA));
	 
	 
--------------------------------------------------------
--  DDL for Table TOPONOMASTICA_CIVICI
--------------------------------------------------------

  CREATE TABLE TOPONOMASTICA_CIVICI 
   (	COD_STATO CHAR(10) NOT NULL, 
	COD_PROV CHAR(10) NOT NULL, 
	COD_COM CHAR(10) NOT NULL, 
	COD_VIA CHAR(20) NOT NULL, 
	COD_CIV CHAR(20) NOT NULL, 
	DES_CIV TINYTEXT NOT NULL, 
	ID_PARAM_UOT_RIF BIGINT NOT NULL, 
	 CONSTRAINT TOPONOMASTICA_CIVICI_PK PRIMARY KEY (COD_STATO, COD_PROV, COD_COM, COD_VIA, COD_CIV));
	 
	 
--------------------------------------------------------
--  DDL for Table UNIQUE_FORM
--------------------------------------------------------

  CREATE TABLE UNIQUE_FORM 
   (	COD_FORM CHAR(10) NOT NULL, 
	DES_FORM TINYTEXT NOT NULL, 
	URL_FORM TINYTEXT NOT NULL, 
	PARAM_FORM TINYTEXT DEFAULT NULL, 
	CLASS_FORM TINYTEXT, 
	 CHECK (COD_FORM IS NOT NULL), 
	 CHECK (DES_FORM IS NOT NULL), 
	 CHECK (URL_FORM IS NOT NULL), 
	 PRIMARY KEY (COD_FORM));
	 	 
--------------------------------------------------------
--  DDL for Table UNIQUE_TASKLIST
--------------------------------------------------------

  CREATE TABLE UNIQUE_TASKLIST 
   (	ID INT NOT NULL, 
	TASKID TINYTEXT, 
	DES_TASK TINYTEXT NOT NULL, 
	TS_CREAZIONE DATETIME NOT NULL, 
	FLG_ESEGUITO CHAR(1) NOT NULL, 
	COD_PAI BIGINT NOT NULL, 
	COD_TIPINT CHAR(10), 
	CNT_TIPINT SMALLINT, 
	FLG_TASKNOT CHAR(1) NOT NULL, 
	FORM CHAR(10) NOT NULL, 
	COD_TMPL BIGINT, 
	RUOLO TINYTEXT, 
	UOT TINYTEXT, 
	CAMPO_FLOW_1 TEXT, 
	CAMPO_FLOW_2 TEXT, 
	CAMPO_FLOW_3 TINYTEXT, 
	CAMPO_FLOW_4 TINYTEXT, 
	CAMPO_FLOW_5 TINYTEXT, 
	CAMPO_FLOW_6 TINYTEXT, 
	CAMPO_FLOW_7 TINYTEXT, 
	CAMPO_FLOW_8 TINYTEXT, 
	CAMPO_FORM_1 TINYTEXT, 
	CAMPO_FORM_2 TEXT, 
	CAMPO_FORM_3 TINYTEXT, 
	CAMPO_FORM_4 TINYTEXT, 
	CAMPO_FORM_5 TINYTEXT, 
	CAMPO_FORM_6 TINYTEXT, 
	CAMPO_FORM_7 TINYTEXT, 
	CAMPO_FORM_8 TINYTEXT, 
	ESITO TINYTEXT, 
	 CHECK (ID IS NOT NULL), 
	 CHECK (DES_TASK IS NOT NULL), 
	 CHECK (TS_CREAZIONE IS NOT NULL), 
	 CHECK (FLG_ESEGUITO IS NOT NULL), 
	 CHECK (COD_PAI IS NOT NULL), 
	 CHECK (FLG_TASKNOT IS NOT NULL), 
	 CHECK (FORM IS NOT NULL), 
	 CHECK (ID IS NOT NULL), 
	 CHECK (COD_PAI IS NOT NULL), 
	 CHECK (TS_CREAZIONE IS NOT NULL), 
	 CHECK (DES_TASK IS NOT NULL), 
	 CHECK (FLG_TASKNOT IS NOT NULL), 
	 CHECK (FLG_ESEGUITO IS NOT NULL), 
	 CHECK (FORM IS NOT NULL), 
	 PRIMARY KEY (ID));
	 
	 
	 
--------------------------------------------------------
--  DDL for Table UOT_INDIRIZZO
--------------------------------------------------------

  CREATE TABLE UOT_INDIRIZZO 
   (	ID BIGINT NOT NULL, 
	UOT BIGINT, 
	INDIRIZZO TINYTEXT, 
	CIVICO CHAR(20), 
	BARRATO CHAR(20), 
	 CONSTRAINT UOT_INDIRIZZO_PK PRIMARY KEY (ID));
	 
	 
--------------------------------------------------------
--  DDL for Table UTENTI
--------------------------------------------------------

  CREATE TABLE UTENTI 
   (	COD_UTE BIGINT NOT NULL, 
	COD_FISC CHAR(16) NOT NULL, 
	NOME TINYTEXT NOT NULL, 
	COGNOME TINYTEXT NOT NULL, 
	ID_PARAM_LVL_ABIL BIGINT NOT NULL, 
	ID_PARAM_UOT BIGINT, 
	ID_PARAM_SER BIGINT NOT NULL, 
	NUM_TEL CHAR(20) DEFAULT NULL, 
	NUM_CELL CHAR(20) DEFAULT NULL, 
	EMAIL CHAR(200) DEFAULT NULL, 
	NOTE TEXT DEFAULT NULL, 
	USERNAME CHAR(50) NOT NULL, 
	MOTIVAZIONE CHAR(1) DEFAULT 'S', 
	PROFILO CHAR(1) DEFAULT 'S', 
	PROBLEMATICHE CHAR(1) DEFAULT 'S', 
	ID_PARAM_PO BIGINT, 
	ID_ASSOCIAZIONE SMALLINT DEFAULT 0, 
	 CONSTRAINT USER_PK PRIMARY KEY (COD_UTE));
	 
	 
--------------------------------------------------------
--  DDL for Table WS_TOKEN
--------------------------------------------------------

  CREATE TABLE WS_TOKEN 
   (	ID CHAR(20), 
	TOKEN CHAR(20), 
	EXPIRES DATETIME, 
	COD_UTE BIGINT, 
	 CONSTRAINT WS_TOKEN_PK PRIMARY KEY (ID)
	 );
	 
--------------------------------------------------------
--  Ref Constraints for Table ANAGRAFE_FAM
--------------------------------------------------------
ALTER TABLE ANAGRAFE_FAM ADD CONSTRAINT FK_1 FOREIGN KEY (COD_ANA) REFERENCES ANAGRAFE_SOC (COD_ANA);
ALTER TABLE ANAGRAFE_FAM ADD CONSTRAINT FK_2 FOREIGN KEY (COD_ANA_FAM) REFERENCES ANAGRAFE_SOC (COD_ANA); 

--------------------------------------------------------
--  Ref Constraints for Table ANAGRAFE_SOC
--------------------------------------------------------
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK1 FOREIGN KEY (COD_STATO_NASC) REFERENCES STATO (COD_STATO);

ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK10 FOREIGN KEY (COD_STATO_RES, COD_PROV_ITA_RES, COD_COM_ITA_RES, COD_VIA_TS_RES, COD_CIV_TS_RES)
	  REFERENCES TOPONOMASTICA_CIVICI (COD_STATO, COD_PROV, COD_COM, COD_VIA, COD_CIV);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK11 FOREIGN KEY (COD_STATO_DOM)
	  REFERENCES STATO (COD_STATO);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK12 FOREIGN KEY (COD_STATO_DOM, COD_PROV_ITA_DOM)
	  REFERENCES PROVINCIA (COD_STATO, COD_PROV);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK13 FOREIGN KEY (COD_STATO_DOM, COD_PROV_ITA_DOM, COD_COM_ITA_DOM)
	  REFERENCES COMUNE (COD_STATO, COD_PROV, COD_COM);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK14 FOREIGN KEY (COD_STATO_DOM, COD_PROV_ITA_DOM, COD_COM_ITA_DOM, COD_VIA_TS_DOM)
	  REFERENCES TOPONOMASTICA (COD_STATO, COD_PROV, COD_COM, COD_VIA);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK15 FOREIGN KEY (COD_STATO_DOM, COD_PROV_ITA_DOM, COD_COM_ITA_DOM, COD_VIA_TS_DOM, COD_CIV_TS_DOM)
	  REFERENCES TOPONOMASTICA_CIVICI (COD_STATO, COD_PROV, COD_COM, COD_VIA, COD_CIV);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK2 FOREIGN KEY (COD_STATO_NASC, COD_PROV_ITA_NASC)
	  REFERENCES PROVINCIA (COD_STATO, COD_PROV);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK3 FOREIGN KEY (COD_STATO_NASC, COD_PROV_ITA_NASC, COD_COM_ITA_NASC)
	  REFERENCES COMUNE (COD_STATO, COD_PROV, COD_COM);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK4 FOREIGN KEY (COD_STATO_CITT)
	  REFERENCES STATO (COD_STATO);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK5 FOREIGN KEY (COD_STATO2_CITT)
	  REFERENCES STATO (COD_STATO); 
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK6 FOREIGN KEY (COD_STATO_RES)
	  REFERENCES STATO (COD_STATO);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK7 FOREIGN KEY (COD_STATO_RES, COD_PROV_ITA_RES)
	  REFERENCES PROVINCIA (COD_STATO, COD_PROV);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK8 FOREIGN KEY (COD_STATO_RES, COD_PROV_ITA_RES, COD_COM_ITA_RES)
	  REFERENCES COMUNE (COD_STATO, COD_PROV, COD_COM);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_FK9 FOREIGN KEY (COD_STATO_RES, COD_PROV_ITA_RES, COD_COM_ITA_RES, COD_VIA_TS_RES)
	  REFERENCES TOPONOMASTICA (COD_STATO, COD_PROV, COD_COM, COD_VIA);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_LFK_DOM FOREIGN KEY (COD_LUOGO_DOM)
	  REFERENCES LUOGO (COD_LUOGO);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_LFK_NASC FOREIGN KEY (COD_LUOGO_NASC)
	  REFERENCES LUOGO (COD_LUOGO);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_LFK_RES FOREIGN KEY (COD_LUOGO_RES)
	  REFERENCES LUOGO (COD_LUOGO);
	  
ALTER TABLE ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_UTENTI_FK FOREIGN KEY (CREATION_USER)
	  REFERENCES UTENTI (COD_UTE);

--------------------------------------------------------
--  Ref Constraints for Table APPUNTAMENTO
--------------------------------------------------------

ALTER TABLE APPUNTAMENTO ADD CONSTRAINT APPUNTAMENTO_FK3 FOREIGN KEY (COD_PAI)
	  REFERENCES PAI (COD_PAI);

--------------------------------------------------------
--  Ref Constraints for Table BUDGET_TIP_INTERVENTO
--------------------------------------------------------
      
ALTER TABLE BUDGET_TIP_INTERVENTO ADD CONSTRAINT TIP_INTERVENTO_IMPEGNO_FK1 FOREIGN KEY (COD_TIPINT)
	  REFERENCES TIPOLOGIA_INTERVENTO (COD_TIPINT);
      
--------------------------------------------------------
--  Ref Constraints for Table BUDGET_TIP_INTERVENTO_UOT
--------------------------------------------------------	  
	  
ALTER TABLE BUDGET_TIP_INTERVENTO_UOT ADD CONSTRAINT TIP_INT_UOT_IMPEGNO_FK1 FOREIGN KEY (COD_TIPINT, COD_ANNO, COD_IMPE)
	  REFERENCES BUDGET_TIP_INTERVENTO (COD_TIPINT, COD_ANNO, COD_IMPE);

--------------------------------------------------------
--  Ref Constraints for Table CARTELLA_SOCIALE
--------------------------------------------------------
	  
ALTER TABLE CARTELLA_SOCIALE ADD CONSTRAINT CARTELLA_SOCIALE_FK1 FOREIGN KEY (COD_ANA)
	  REFERENCES ANAGRAFE_SOC (COD_ANA);

--------------------------------------------------------
--  Ref Constraints for Table COMUNE
--------------------------------------------------------
	  
ALTER TABLE COMUNE ADD CONSTRAINT COMUNE_FK1 FOREIGN KEY (COD_STATO, COD_PROV)
	  REFERENCES PROVINCIA (COD_STATO, COD_PROV);

--------------------------------------------------------
--  Ref Constraints for Table CONTATTO
--------------------------------------------------------
	  
ALTER TABLE CONTATTO ADD CONSTRAINT CONTATTO_FK2 FOREIGN KEY (COD_ANA)
	  REFERENCES ANAGRAFE_SOC (COD_ANA);

--------------------------------------------------------
--  Ref Constraints for Table FATTURA
--------------------------------------------------------
	  
ALTER TABLE FATTURA ADD CONSTRAINT FATTURA_FK1 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT);
	  
ALTER TABLE FATTURA ADD CONSTRAINT FATTURA_FK2 FOREIGN KEY (COD_ANA)
	  REFERENCES ANAGRAFE_SOC (COD_ANA);

--------------------------------------------------------
--  Ref Constraints for Table FATTURA_DETTAGLIO
--------------------------------------------------------

ALTER TABLE FATTURA_DETTAGLIO ADD CONSTRAINT FATTURA_DETTAGLIO_FK1 FOREIGN KEY (ID_FATT)
	  REFERENCES FATTURA (ID_FATT);
	  
ALTER TABLE FATTURA_DETTAGLIO ADD CONSTRAINT FATTURA_DETTAGLIO_FK3 FOREIGN KEY (COD_TIPINT)
	  REFERENCES TIPOLOGIA_INTERVENTO (COD_TIPINT);

--------------------------------------------------------
--  Ref Constraints for Table FATTURA_MESI_PRECEDENTI
--------------------------------------------------------

ALTER TABLE FATTURA_MESI_PRECEDENTI ADD CONSTRAINT FATTURA_MESI_PREC_FK1 FOREIGN KEY (ID_FATT_PRINC)
	  REFERENCES FATTURA (ID_FATT);
	  
ALTER TABLE FATTURA_MESI_PRECEDENTI ADD CONSTRAINT FATTURA_MESI_PREC_FK2 FOREIGN KEY (ID_FATT_CORR)
	  REFERENCES FATTURA (ID_FATT);

--------------------------------------------------------
--  Ref Constraints for Table INTERVENTI_ASSOCIATI
--------------------------------------------------------
	  
ALTER TABLE INTERVENTI_ASSOCIATI ADD CONSTRAINT INTERVENTI_ASSOCIATI_PAI__FK1 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT); 
	  
ALTER TABLE INTERVENTI_ASSOCIATI ADD CONSTRAINT INTERVENTI_ASSOCIATI_PAI__FK2 FOREIGN KEY (COD_PAI1, COD_TIPINT1, CNT_TIPINT1)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT);

--------------------------------------------------------
--  Ref Constraints for Table LIBERATORIA
--------------------------------------------------------
	  
ALTER TABLE LIBERATORIA ADD CONSTRAINT LIBERATORIA_ANAGRAFE_SOC_FK1 FOREIGN KEY (COD_ANA)
	  REFERENCES ANAGRAFE_SOC (COD_ANA); 
	  
ALTER TABLE LIBERATORIA ADD CONSTRAINT LIBERATORIA_ASSOCIAZIONE_FK1 FOREIGN KEY (ID_ASSOCIAZIONE)
	  REFERENCES ASSOCIAZIONE (ID);

--------------------------------------------------------
--  Ref Constraints for Table LOG_ANAGRAFE
--------------------------------------------------------

ALTER TABLE LOG_ANAGRAFE ADD CONSTRAINT LOG_ANAGRAFE_FK2 FOREIGN KEY (COD_ANA)
	  REFERENCES ANAGRAFE_SOC (COD_ANA); 
	  
ALTER TABLE LOG_ANAGRAFE ADD CONSTRAINT LOG_ANAGRAFE_FK3 FOREIGN KEY (COD_PAI)
	  REFERENCES PAI (COD_PAI);

--------------------------------------------------------
--  Ref Constraints for Table LOG_MESSAGGI
--------------------------------------------------------
	  
ALTER TABLE LOG_MESSAGGI ADD CONSTRAINT LOG_MESSAGGI_FK1 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT);

--------------------------------------------------------
--  Ref Constraints for Table LUOGO
--------------------------------------------------------
	  
ALTER TABLE LUOGO ADD CONSTRAINT LUOGO_FK1 FOREIGN KEY (COD_STATO)
	  REFERENCES STATO (COD_STATO); 
	  
ALTER TABLE LUOGO ADD 	 CONSTRAINT LUOGO_FK2 FOREIGN KEY (COD_STATO, COD_PROV, COD_COM, COD_VIA, COD_CIV)
	  REFERENCES TOPONOMASTICA_CIVICI (COD_STATO, COD_PROV, COD_COM, COD_VIA, COD_CIV); 
	  
ALTER TABLE LUOGO ADD 	 CONSTRAINT LUOGO_FK3 FOREIGN KEY (COD_STATO, COD_PROV)
	  REFERENCES PROVINCIA (COD_STATO, COD_PROV); 
	  
ALTER TABLE LUOGO ADD 	 CONSTRAINT LUOGO_FK4 FOREIGN KEY (COD_STATO, COD_PROV, COD_COM)
	  REFERENCES COMUNE (COD_STATO, COD_PROV, COD_COM); 
	  
ALTER TABLE LUOGO ADD 	 CONSTRAINT LUOGO_FK5 FOREIGN KEY (COD_STATO, COD_PROV, COD_COM, COD_VIA)
	  REFERENCES TOPONOMASTICA (COD_STATO, COD_PROV, COD_COM, COD_VIA);

--------------------------------------------------------
--  Ref Constraints for Table MANDATO
--------------------------------------------------------
	  
ALTER TABLE MANDATO ADD CONSTRAINT MANDATO_FK1 FOREIGN KEY (COD_ANA_BENEFICIARIO)
	  REFERENCES ANAGRAFE_SOC (COD_ANA); 
	  
ALTER TABLE MANDATO ADD CONSTRAINT MANDATO_FK2 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT);
	  
ALTER TABLE MANDATO ADD CONSTRAINT MANDATO_FK3 FOREIGN KEY (COD_ANA_DELEGANTE)
	  REFERENCES ANAGRAFE_SOC (COD_ANA);

--------------------------------------------------------
--  Ref Constraints for Table MANDATO_DETTAGLIO
--------------------------------------------------------
	  
ALTER TABLE MANDATO_DETTAGLIO ADD CONSTRAINT MANDATO_DETTAGLIO_FK1 FOREIGN KEY (ID_MAN)
	  REFERENCES MANDATO (ID_MAN); 
	  
ALTER TABLE MANDATO_DETTAGLIO ADD CONSTRAINT MANDATO_DETTAGLIO_FK3 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT);

--------------------------------------------------------
--  Ref Constraints for Table NOTE_CONDIVISE
--------------------------------------------------------
	  
ALTER TABLE MAP_DATI_SPEC_TIPINT ADD FOREIGN KEY (COD_TIPINT)
	  REFERENCES TIPOLOGIA_INTERVENTO (COD_TIPINT); 
	  
ALTER TABLE MAP_DATI_SPEC_TIPINT ADD FOREIGN KEY (COD_CAMPO)
	  REFERENCES DATI_SPECIFICI (COD_CAMPO);

--------------------------------------------------------
--  Ref Constraints for Table ANAGRAFE_FAM
--------------------------------------------------------
	  
ALTER TABLE NOTE_CONDIVISE ADD CONSTRAINT NOTE_CONDIVISE_ANAGRAFE_S_FK1 FOREIGN KEY (COD_ANA)
	  REFERENCES ANAGRAFE_SOC (COD_ANA); 
	  
ALTER TABLE NOTE_CONDIVISE ADD CONSTRAINT NOTE_FK1 FOREIGN KEY (COD_UTE)
	  REFERENCES UTENTI (COD_UTE);

--------------------------------------------------------
--  Ref Constraints for Table PAI
--------------------------------------------------------
	  
ALTER TABLE PAI ADD CONSTRAINT PAI_FK1 FOREIGN KEY (COD_ANA)
	  REFERENCES CARTELLA_SOCIALE (COD_ANA);

--------------------------------------------------------
--  Ref Constraints for Table PAI_ANAGRAFICA
--------------------------------------------------------
	  
ALTER TABLE PAI_ANAGRAFICA ADD CONSTRAINT PAI_ANAGRAFICA_FK1 FOREIGN KEY (COD_PAI)
	  REFERENCES PAI (COD_PAI); 
	  
ALTER TABLE PAI_ANAGRAFICA ADD CONSTRAINT PAI_ANAGRAFICA_FK2 FOREIGN KEY (COD_ANA_SOC)
	  REFERENCES ANAGRAFE_SOC (COD_ANA);

--------------------------------------------------------
--  Ref Constraints for Table PAI_CDG
--------------------------------------------------------
	  
ALTER TABLE PAI_CDG ADD CONSTRAINT PAI_CDG_FK1 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT, ANNO_EFF, MESE_EFF, COD_ANNO, COD_IMPE)
	  REFERENCES PAI_INTERVENTO_MESE (COD_PAI, COD_TIPINT, CNT_TIPINT, ANNO_EFF, MESE_EFF, ANNO, COD_IMP);
	  
ALTER TABLE PAI_CDG ADD CONSTRAINT PAI_CDG_FK2 FOREIGN KEY (COD_ANA)
	  REFERENCES ANAGRAFE_SOC (COD_ANA);

--------------------------------------------------------
--  Ref Constraints for Table PAI_DOCUMENTO
--------------------------------------------------------

ALTER TABLE PAI_DOCUMENTO ADD CONSTRAINT PAI_DOCUMENTO_FK1 FOREIGN KEY (COD_PAI)
	  REFERENCES PAI (COD_PAI); 
	  
ALTER TABLE PAI_DOCUMENTO ADD CONSTRAINT PAI_DOCUMENTO_FK2 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT);
	  
--------------------------------------------------------
--  Ref Constraints for Table PAI_EVENTO
--------------------------------------------------------
	  
ALTER TABLE PAI_EVENTO ADD CONSTRAINT PAI_EVENTO_FK1 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT); 
	  
ALTER TABLE PAI_EVENTO ADD CONSTRAINT PAI_EVENTO_FK3 FOREIGN KEY (ID_DETERMINA)
	  REFERENCES DETERMINE (ID_DETERMINA); 
	  
ALTER TABLE PAI_EVENTO ADD CONSTRAINT PAI_EVENTO_FK6 FOREIGN KEY (COD_PAI)
	  REFERENCES PAI (COD_PAI);
	  
--------------------------------------------------------
--  Ref Constraints for Table PAI_INTERVENTO
--------------------------------------------------------	  
	  
ALTER TABLE PAI_INTERVENTO ADD CONSTRAINT PAI_INTERVENTO_ANAGRAFE_S_FK1 FOREIGN KEY (DS_COD_ANA_RICHIEDENTE)
	  REFERENCES ANAGRAFE_SOC (COD_ANA); 
	  
ALTER TABLE PAI_INTERVENTO ADD CONSTRAINT PAI_INTERVENTO_ASSOCIAZIO_FK1 FOREIGN KEY (ID_ASSOCIAZIONE)
	  REFERENCES ASSOCIAZIONE (ID); 
	  
ALTER TABLE PAI_INTERVENTO ADD CONSTRAINT PAI_INTERVENTO_FK1 FOREIGN KEY (COD_PAI)
	  REFERENCES PAI (COD_PAI); 
	  
ALTER TABLE PAI_INTERVENTO ADD CONSTRAINT PAI_INTERVENTO_FK2 FOREIGN KEY (COD_TIPINT)
	  REFERENCES TIPOLOGIA_INTERVENTO (COD_TIPINT); 
	  
ALTER TABLE PAI_INTERVENTO ADD CONSTRAINT PAI_INTERVENTO_FK4 FOREIGN KEY (DS_COD_ANA_BENEF)
	  REFERENCES ANAGRAFE_SOC (COD_ANA);

--------------------------------------------------------
--  Ref Constraints for Table PAI_INTERVENTO_ANAGRAFICA
--------------------------------------------------------
	  
ALTER TABLE PAI_INTERVENTO_ANAGRAFICA ADD CONSTRAINT PAI_INTERVENTO_ANAGRAFICA_FK1 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT); 
	  
ALTER TABLE PAI_INTERVENTO_ANAGRAFICA ADD CONSTRAINT PAI_INTERVENTO_ANAGRAFICA_FK2 FOREIGN KEY (COD_ANA_SOC)
	  REFERENCES ANAGRAFE_SOC (COD_ANA);

--------------------------------------------------------
--  Ref Constraints for Table PAI_INTERVENTO_CIV_OBB
--------------------------------------------------------
	  
ALTER TABLE PAI_INTERVENTO_CIV_OBB ADD CONSTRAINT PAI_INTERVENTO_CIV_OBB_FK1 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT); 
	  
ALTER TABLE PAI_INTERVENTO_CIV_OBB ADD CONSTRAINT PAI_INTERVENTO_CIV_OBB_FK2 FOREIGN KEY (COD_ANA_CO)
	  REFERENCES ANAGRAFE_SOC (COD_ANA);
	  
--------------------------------------------------------
--  Ref Constraints for Table PAI_INTERVENTO_MESE
--------------------------------------------------------	  
	  
ALTER TABLE PAI_INTERVENTO_MESE ADD CONSTRAINT PAI_INTERVENTO_MESE_FK1 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT); 
	  
ALTER TABLE PAI_INTERVENTO_MESE ADD CONSTRAINT PAI_INTERVENTO_MESE_FK2 FOREIGN KEY (ID_FATT_DETTAGLIO)
	  REFERENCES FATTURA_DETTAGLIO (ID_FATT_DETTAGLIO); 
	  
ALTER TABLE PAI_INTERVENTO_MESE ADD CONSTRAINT PAI_INTERVENTO_MESE_FK3 FOREIGN KEY (COD_TIPINT, ANNO, COD_IMP)
	  REFERENCES BUDGET_TIP_INTERVENTO (COD_TIPINT, COD_ANNO, COD_IMPE); 
	  
ALTER TABLE PAI_INTERVENTO_MESE ADD CONSTRAINT PAI_INTERVENTO_MESE_FK4 FOREIGN KEY (ID_MAN_DETTAGLIO)
	  REFERENCES MANDATO_DETTAGLIO (ID_MAN_DETTAGLIO); 
	  
ALTER TABLE PAI_INTERVENTO_MESE ADD CONSTRAINT PAI_INTERVENTO_MESE_PARAM_FK1 FOREIGN KEY (ID_PARAM_FASCIA)
	  REFERENCES PARAMETRI_INDATA (ID_PARAM_INDATA);

--------------------------------------------------------
--  Ref Constraints for Table PAI_MACRO_PROBLEMATICHE
--------------------------------------------------------
	  
ALTER TABLE PAI_MACRO_PROBLEMATICHE ADD CONSTRAINT PAI_MP_FK_PAI FOREIGN KEY (COD_PAI)
	  REFERENCES PAI (COD_PAI);

--------------------------------------------------------
--  Ref Constraints for Table PAI_MICRO_PROBLEMATICHE
--------------------------------------------------------
	  
ALTER TABLE PAI_MICRO_PROBLEMATICHE ADD CONSTRAINT PAI_MIP_FK_MAP FOREIGN KEY (COD_PAI, IP_MACRO_PROBLEMATICA)
	  REFERENCES PAI_MACRO_PROBLEMATICHE (COD_PAI, IP_MACRO_PROBLEMATICA); 
	  
ALTER TABLE PAI_MICRO_PROBLEMATICHE ADD CONSTRAINT PAI_MIP_FK_PAI FOREIGN KEY (COD_PAI)
	  REFERENCES PAI (COD_PAI);
	  
--------------------------------------------------------
--  Ref Constraints for Table PARAMETRI
--------------------------------------------------------	  
	  
ALTER TABLE PARAMETRI ADD CONSTRAINT PARAMETRI_FK1 FOREIGN KEY (TIP_PARAM)
	  REFERENCES TIPOLOGIA_PARAMETRI (TIP_PARAM);
	  
--------------------------------------------------------
--  Ref Constraints for Table PROVINCIA
--------------------------------------------------------	  
	  
ALTER TABLE PROVINCIA ADD CONSTRAINT PROVINCIA_FK1 FOREIGN KEY (COD_STATO)
	  REFERENCES STATO (COD_STATO);
	  
--------------------------------------------------------
--  Ref Constraints for Table RICEVUTA_CASSA
--------------------------------------------------------	  
	  
ALTER TABLE RICEVUTA_CASSA ADD 	 CONSTRAINT RICEVUTA_CASSA_PAI_FK1 FOREIGN KEY (COD_PAI)
	  REFERENCES PAI (COD_PAI);
	  
--------------------------------------------------------
--  Ref Constraints for Table STRUTTURA
--------------------------------------------------------	  
	  
ALTER TABLE STRUTTURA ADD CONSTRAINT STRUTTURA_TIPOLOGIA_INTER_FK1 FOREIGN KEY (COD_TIPINT)
	  REFERENCES TIPOLOGIA_INTERVENTO (COD_TIPINT); 
	  
ALTER TABLE STRUTTURA ADD CONSTRAINT FK_ENTE FOREIGN KEY (ID_ENTE)
	  REFERENCES ENTE (ID);
	  
--------------------------------------------------------
--  Ref Constraints for Table TARIFFA
--------------------------------------------------------	  
	  
ALTER TABLE TARIFFA ADD CONSTRAINT STRUTTURA_FK FOREIGN KEY (ID_STRUTTURA)
	  REFERENCES STRUTTURA (ID);
	 
--------------------------------------------------------
--  Ref Constraints for Table TIPOLOGIA_INTERVENTO
--------------------------------------------------------
	 
ALTER TABLE TIPOLOGIA_INTERVENTO ADD CONSTRAINT FK_IP_PI FOREIGN KEY (IP_ALIQUOTA_IVA)
	  REFERENCES PARAMETRI_INDATA (ID_PARAM_INDATA); 
	  
ALTER TABLE TIPOLOGIA_INTERVENTO ADD CONSTRAINT TIPOLOGIA_INTERVENTO_FK4 FOREIGN KEY (COD_LISTA_ATT)
	  REFERENCES LISTA_ATTESA (COD_LISTA_ATT);
	  
--------------------------------------------------------
--  Ref Constraints for Table TOPONOMASTICA
--------------------------------------------------------

ALTER TABLE TOPONOMASTICA ADD CONSTRAINT TOPONOMASTICA_FK1 FOREIGN KEY (COD_STATO, COD_PROV, COD_COM)
	  REFERENCES COMUNE (COD_STATO, COD_PROV, COD_COM);

--------------------------------------------------------
--  Ref Constraints for Table TOPONOMASTICA_CIVICI
--------------------------------------------------------

ALTER TABLE TOPONOMASTICA_CIVICI ADD CONSTRAINT TOPONOMASTICA_CIVICI_FK1 FOREIGN KEY (COD_STATO, COD_PROV, COD_COM, COD_VIA)
	  REFERENCES TOPONOMASTICA (COD_STATO, COD_PROV, COD_COM, COD_VIA);
	  
--------------------------------------------------------
--  Ref Constraints for Table UNIQUE_TASKLIST
--------------------------------------------------------	  
	  
ALTER TABLE UNIQUE_TASKLIST ADD CONSTRAINT UNIQUE_TASKLIST_FK1 FOREIGN KEY (FORM)
	  REFERENCES UNIQUE_FORM (COD_FORM); 
	  
ALTER TABLE UNIQUE_TASKLIST ADD CONSTRAINT UNIQUE_TASKLIST_FK2 FOREIGN KEY (COD_PAI)
	  REFERENCES PAI (COD_PAI); 
	  
ALTER TABLE UNIQUE_TASKLIST ADD CONSTRAINT UNIQUE_TASKLIST_FK3 FOREIGN KEY (COD_PAI, COD_TIPINT, CNT_TIPINT)
	  REFERENCES PAI_INTERVENTO (COD_PAI, COD_TIPINT, CNT_TIPINT);
	  
--------------------------------------------------------
--  Ref Constraints for Table UTENTI
--------------------------------------------------------	  
	  
ALTER TABLE UTENTI ADD CONSTRAINT UTENTI_ASSOCIAZIONE_FK1 FOREIGN KEY (ID_ASSOCIAZIONE)
	  REFERENCES ASSOCIAZIONE (ID); 
	  
ALTER TABLE UTENTI ADD CONSTRAINT UTENTI_FK1 FOREIGN KEY (ID_PARAM_LVL_ABIL)
	  REFERENCES PARAMETRI_INDATA (ID_PARAM_INDATA); 
	  
ALTER TABLE UTENTI ADD CONSTRAINT UTENTI_FK2 FOREIGN KEY (ID_PARAM_UOT)
	  REFERENCES PARAMETRI_INDATA (ID_PARAM_INDATA); 
	  
ALTER TABLE UTENTI ADD CONSTRAINT UTENTI_FK3 FOREIGN KEY (ID_PARAM_SER)
	  REFERENCES PARAMETRI_INDATA (ID_PARAM_INDATA); 
	  
ALTER TABLE UTENTI ADD CONSTRAINT UTENTI_PARAMETRI_INDATA_FK1 FOREIGN KEY (ID_PARAM_PO)
	  REFERENCES PARAMETRI_INDATA (ID_PARAM_INDATA);
  
--------------------------------------------------------
--  Ref Constraints for Table WS_TOKEN
--------------------------------------------------------  
  
ALTER TABLE WS_TOKEN ADD CONSTRAINT WS_TOKEN_UTENTI_FK1 FOREIGN KEY (COD_UTE)
	  REFERENCES UTENTI (COD_UTE);
