//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for altro_tipo_intervento_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="altro_tipo_intervento_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="da0100"/>
 *     &lt;enumeration value="da0200"/>
 *     &lt;enumeration value="da0300"/>
 *     &lt;enumeration value="da0400"/>
 *     &lt;enumeration value="da0500"/>
 *     &lt;enumeration value="da0600"/>
 *     &lt;enumeration value="da0700"/>
 *     &lt;enumeration value="da0800"/>
 *     &lt;enumeration value="da0900"/>
 *     &lt;enumeration value="da1000"/>
 *     &lt;enumeration value="da1100"/>
 *     &lt;enumeration value="da1200"/>
 *     &lt;enumeration value="da1300"/>
 *     &lt;enumeration value="da1400"/>
 *     &lt;enumeration value="da1500"/>
 *     &lt;enumeration value="da1600"/>
 *     &lt;enumeration value="da1700"/>
 *     &lt;enumeration value="da1800"/>
 *     &lt;enumeration value="da1900"/>
 *     &lt;enumeration value="da2000"/>
 *     &lt;enumeration value="db0100"/>
 *     &lt;enumeration value="db0200"/>
 *     &lt;enumeration value="db0300"/>
 *     &lt;enumeration value="db0400"/>
 *     &lt;enumeration value="db0600"/>
 *     &lt;enumeration value="db0700"/>
 *     &lt;enumeration value="db0800"/>
 *     &lt;enumeration value="db0900"/>
 *     &lt;enumeration value="db1000"/>
 *     &lt;enumeration value="db1100"/>
 *     &lt;enumeration value="dd0100"/>
 *     &lt;enumeration value="dd0200"/>
 *     &lt;enumeration value="dd0300"/>
 *     &lt;enumeration value="dd0400"/>
 *     &lt;enumeration value="dd0500"/>
 *     &lt;enumeration value="dd0600"/>
 *     &lt;enumeration value="dd0700"/>
 *     &lt;enumeration value="dd0800"/>
 *     &lt;enumeration value="dd0900"/>
 *     &lt;enumeration value="dd1000"/>
 *     &lt;enumeration value="dd1100"/>
 *     &lt;enumeration value="dd1200"/>
 *     &lt;enumeration value="dd1300"/>
 *     &lt;enumeration value="dd1400"/>
 *     &lt;enumeration value="dd1500"/>
 *     &lt;enumeration value="dd1600"/>
 *     &lt;enumeration value="dd1700"/>
 *     &lt;enumeration value="dd1800"/>
 *     &lt;enumeration value="dd1900"/>
 *     &lt;enumeration value="dfB200"/>
 *     &lt;enumeration value="dfB100"/>
 *     &lt;enumeration value="dfB300"/>
 *     &lt;enumeration value="dfB400"/>
 *     &lt;enumeration value="dgA100"/>
 *     &lt;enumeration value="dgA200"/>
 *     &lt;enumeration value="dgA300"/>
 *     &lt;enumeration value="dc0100"/>
 *     &lt;enumeration value="dc0200"/>
 *     &lt;enumeration value="dc0600"/>
 *     &lt;enumeration value="dc0700"/>
 *     &lt;enumeration value="dc0800"/>
 *     &lt;enumeration value="dc0900"/>
 *     &lt;enumeration value="dc1000"/>
 *     &lt;enumeration value="dc1200"/>
 *     &lt;enumeration value="dc1300"/>
 *     &lt;enumeration value="dc1400"/>
 *     &lt;enumeration value="dc0300"/>
 *     &lt;enumeration value="dc0400"/>
 *     &lt;enumeration value="dc1500"/>
 *     &lt;enumeration value="dc1100"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "altro_tipo_intervento_type")
@XmlEnum
public enum AltroTipoInterventoType {

    @XmlEnumValue("da0100")
    DA_0100("da0100"),
    @XmlEnumValue("da0200")
    DA_0200("da0200"),
    @XmlEnumValue("da0300")
    DA_0300("da0300"),
    @XmlEnumValue("da0400")
    DA_0400("da0400"),
    @XmlEnumValue("da0500")
    DA_0500("da0500"),
    @XmlEnumValue("da0600")
    DA_0600("da0600"),
    @XmlEnumValue("da0700")
    DA_0700("da0700"),
    @XmlEnumValue("da0800")
    DA_0800("da0800"),
    @XmlEnumValue("da0900")
    DA_0900("da0900"),
    @XmlEnumValue("da1000")
    DA_1000("da1000"),
    @XmlEnumValue("da1100")
    DA_1100("da1100"),
    @XmlEnumValue("da1200")
    DA_1200("da1200"),
    @XmlEnumValue("da1300")
    DA_1300("da1300"),
    @XmlEnumValue("da1400")
    DA_1400("da1400"),
    @XmlEnumValue("da1500")
    DA_1500("da1500"),
    @XmlEnumValue("da1600")
    DA_1600("da1600"),
    @XmlEnumValue("da1700")
    DA_1700("da1700"),
    @XmlEnumValue("da1800")
    DA_1800("da1800"),
    @XmlEnumValue("da1900")
    DA_1900("da1900"),
    @XmlEnumValue("da2000")
    DA_2000("da2000"),
    @XmlEnumValue("db0100")
    DB_0100("db0100"),
    @XmlEnumValue("db0200")
    DB_0200("db0200"),
    @XmlEnumValue("db0300")
    DB_0300("db0300"),
    @XmlEnumValue("db0400")
    DB_0400("db0400"),
    @XmlEnumValue("db0600")
    DB_0600("db0600"),
    @XmlEnumValue("db0700")
    DB_0700("db0700"),
    @XmlEnumValue("db0800")
    DB_0800("db0800"),
    @XmlEnumValue("db0900")
    DB_0900("db0900"),
    @XmlEnumValue("db1000")
    DB_1000("db1000"),
    @XmlEnumValue("db1100")
    DB_1100("db1100"),
    @XmlEnumValue("dd0100")
    DD_0100("dd0100"),
    @XmlEnumValue("dd0200")
    DD_0200("dd0200"),
    @XmlEnumValue("dd0300")
    DD_0300("dd0300"),
    @XmlEnumValue("dd0400")
    DD_0400("dd0400"),
    @XmlEnumValue("dd0500")
    DD_0500("dd0500"),
    @XmlEnumValue("dd0600")
    DD_0600("dd0600"),
    @XmlEnumValue("dd0700")
    DD_0700("dd0700"),
    @XmlEnumValue("dd0800")
    DD_0800("dd0800"),
    @XmlEnumValue("dd0900")
    DD_0900("dd0900"),
    @XmlEnumValue("dd1000")
    DD_1000("dd1000"),
    @XmlEnumValue("dd1100")
    DD_1100("dd1100"),
    @XmlEnumValue("dd1200")
    DD_1200("dd1200"),
    @XmlEnumValue("dd1300")
    DD_1300("dd1300"),
    @XmlEnumValue("dd1400")
    DD_1400("dd1400"),
    @XmlEnumValue("dd1500")
    DD_1500("dd1500"),
    @XmlEnumValue("dd1600")
    DD_1600("dd1600"),
    @XmlEnumValue("dd1700")
    DD_1700("dd1700"),
    @XmlEnumValue("dd1800")
    DD_1800("dd1800"),
    @XmlEnumValue("dd1900")
    DD_1900("dd1900"),
    @XmlEnumValue("dfB200")
    DF_B_200("dfB200"),
    @XmlEnumValue("dfB100")
    DF_B_100("dfB100"),
    @XmlEnumValue("dfB300")
    DF_B_300("dfB300"),
    @XmlEnumValue("dfB400")
    DF_B_400("dfB400"),
    @XmlEnumValue("dgA100")
    DG_A_100("dgA100"),
    @XmlEnumValue("dgA200")
    DG_A_200("dgA200"),
    @XmlEnumValue("dgA300")
    DG_A_300("dgA300"),
    @XmlEnumValue("dc0100")
    DC_0100("dc0100"),
    @XmlEnumValue("dc0200")
    DC_0200("dc0200"),
    @XmlEnumValue("dc0600")
    DC_0600("dc0600"),
    @XmlEnumValue("dc0700")
    DC_0700("dc0700"),
    @XmlEnumValue("dc0800")
    DC_0800("dc0800"),
    @XmlEnumValue("dc0900")
    DC_0900("dc0900"),
    @XmlEnumValue("dc1000")
    DC_1000("dc1000"),
    @XmlEnumValue("dc1200")
    DC_1200("dc1200"),
    @XmlEnumValue("dc1300")
    DC_1300("dc1300"),
    @XmlEnumValue("dc1400")
    DC_1400("dc1400"),
    @XmlEnumValue("dc0300")
    DC_0300("dc0300"),
    @XmlEnumValue("dc0400")
    DC_0400("dc0400"),
    @XmlEnumValue("dc1500")
    DC_1500("dc1500"),
    @XmlEnumValue("dc1100")
    DC_1100("dc1100");
    private final String value;

    AltroTipoInterventoType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AltroTipoInterventoType fromValue(String v) {
        for (AltroTipoInterventoType c: AltroTipoInterventoType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
