//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for diagnosi_sociale_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="diagnosi_sociale_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="C00"/>
 *     &lt;enumeration value="C02"/>
 *     &lt;enumeration value="C04"/>
 *     &lt;enumeration value="C05"/>
 *     &lt;enumeration value="C06"/>
 *     &lt;enumeration value="C07"/>
 *     &lt;enumeration value="C08"/>
 *     &lt;enumeration value="C09"/>
 *     &lt;enumeration value="C10"/>
 *     &lt;enumeration value="C11"/>
 *     &lt;enumeration value="C12"/>
 *     &lt;enumeration value="C13"/>
 *     &lt;enumeration value="C14"/>
 *     &lt;enumeration value="C15"/>
 *     &lt;enumeration value="C16"/>
 *     &lt;enumeration value="C17"/>
 *     &lt;enumeration value="C18"/>
 *     &lt;enumeration value="C19"/>
 *     &lt;enumeration value="C21"/>
 *     &lt;enumeration value="C22"/>
 *     &lt;enumeration value="C23"/>
 *     &lt;enumeration value="C24"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "diagnosi_sociale_type")
@XmlEnum
public enum DiagnosiSocialeType {

    @XmlEnumValue("C00")
    C_00("C00"),
    @XmlEnumValue("C02")
    C_02("C02"),
    @XmlEnumValue("C04")
    C_04("C04"),
    @XmlEnumValue("C05")
    C_05("C05"),
    @XmlEnumValue("C06")
    C_06("C06"),
    @XmlEnumValue("C07")
    C_07("C07"),
    @XmlEnumValue("C08")
    C_08("C08"),
    @XmlEnumValue("C09")
    C_09("C09"),
    @XmlEnumValue("C10")
    C_10("C10"),
    @XmlEnumValue("C11")
    C_11("C11"),
    @XmlEnumValue("C12")
    C_12("C12"),
    @XmlEnumValue("C13")
    C_13("C13"),
    @XmlEnumValue("C14")
    C_14("C14"),
    @XmlEnumValue("C15")
    C_15("C15"),
    @XmlEnumValue("C16")
    C_16("C16"),
    @XmlEnumValue("C17")
    C_17("C17"),
    @XmlEnumValue("C18")
    C_18("C18"),
    @XmlEnumValue("C19")
    C_19("C19"),
    @XmlEnumValue("C21")
    C_21("C21"),
    @XmlEnumValue("C22")
    C_22("C22"),
    @XmlEnumValue("C23")
    C_23("C23"),
    @XmlEnumValue("C24")
    C_24("C24");
    private final String value;

    DiagnosiSocialeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DiagnosiSocialeType fromValue(String v) {
        for (DiagnosiSocialeType c: DiagnosiSocialeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
