//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for famiglia_affidataria_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="famiglia_affidataria_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codice_individuale_anagrafe_comunale">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codice_nucleo_familiare_anagrafe_comunale">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cognome">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nome">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="data_nascita" type="{}data_type"/>
 *         &lt;element name="sesso" type="{}sesso_type"/>
 *         &lt;element name="informazioni_territoriali_nascita" type="{}informazioni_territoriali_type"/>
 *         &lt;element name="cittadinanza" type="{}stato_type" maxOccurs="2"/>
 *         &lt;element name="codice_fiscale" type="{}codice_fiscale_type"/>
 *         &lt;element name="stato_civile" type="{}stato_civile_type"/>
 *         &lt;element name="comune_residenza" type="{}comune_italiano_type"/>
 *         &lt;element name="indirizzo_residenza" type="{}indirizzo_type"/>
 *         &lt;element name="telefono_casa">
 *           &lt;simpleType>
 *             &lt;restriction base="{}telefono_type">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="telefono_lavoro">
 *           &lt;simpleType>
 *             &lt;restriction base="{}telefono_type">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="telefono_cellulare">
 *           &lt;simpleType>
 *             &lt;restriction base="{}telefono_type">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="livello_condivisione_altri_operatori" type="{}livello_condivisione_altri_operatori_type"/>
 *         &lt;element name="disponibilita" type="{}disponibilita_famiglia_affidataria_type"/>
 *         &lt;element name="data_inizio_disponibilita" type="{}data_type"/>
 *         &lt;element name="data_fine_disponibilita" type="{}data_type"/>
 *         &lt;element name="tipologia_affido" type="{}tipologia_affido_type"/>
 *         &lt;element name="modalita_affido" type="{}modalita_affido_type"/>
 *         &lt;element name="gratuito" type="{}si_no_type"/>
 *         &lt;element name="costo_mensile" type="{}importo_type"/>
 *         &lt;element name="numero_figli_famiglia">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *               &lt;pattern value="[0-9]{0,3}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="eta_media_figli_famiglia">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *               &lt;pattern value="[0-9]{0,3}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="posti_disponibili">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *               &lt;pattern value="[0-9]{0,3}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="campo_note" type="{}note_type"/>
 *         &lt;element name="codice_fiscale_operatore_riferimento" type="{}codice_fiscale_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "famiglia_affidataria_type", propOrder = {
    "codiceIndividualeAnagrafeComunale",
    "codiceNucleoFamiliareAnagrafeComunale",
    "cognome",
    "nome",
    "dataNascita",
    "sesso",
    "informazioniTerritorialiNascita",
    "cittadinanza",
    "codiceFiscale",
    "statoCivile",
    "comuneResidenza",
    "indirizzoResidenza",
    "telefonoCasa",
    "telefonoLavoro",
    "telefonoCellulare",
    "livelloCondivisioneAltriOperatori",
    "disponibilita",
    "dataInizioDisponibilita",
    "dataFineDisponibilita",
    "tipologiaAffido",
    "modalitaAffido",
    "gratuito",
    "costoMensile",
    "numeroFigliFamiglia",
    "etaMediaFigliFamiglia",
    "postiDisponibili",
    "campoNote",
    "codiceFiscaleOperatoreRiferimento"
})
public class FamigliaAffidatariaType {

    @XmlElement(name = "codice_individuale_anagrafe_comunale", required = true)
    protected String codiceIndividualeAnagrafeComunale;
    @XmlElement(name = "codice_nucleo_familiare_anagrafe_comunale", required = true)
    protected String codiceNucleoFamiliareAnagrafeComunale;
    @XmlElement(required = true)
    protected String cognome;
    @XmlElement(required = true)
    protected String nome;
    @XmlElement(name = "data_nascita", required = true)
    protected String dataNascita;
    @XmlElement(required = true)
    protected SessoType sesso;
    @XmlElement(name = "informazioni_territoriali_nascita", required = true)
    protected InformazioniTerritorialiType informazioniTerritorialiNascita;
    @XmlElement(required = true)
    protected List<StatoType> cittadinanza;
    @XmlElement(name = "codice_fiscale", required = true)
    protected String codiceFiscale;
    @XmlElement(name = "stato_civile", required = true, nillable = true)
    protected String statoCivile;
    @XmlElement(name = "comune_residenza", required = true)
    protected String comuneResidenza;
    @XmlElement(name = "indirizzo_residenza", required = true, nillable = true)
    protected String indirizzoResidenza;
    @XmlElement(name = "telefono_casa", required = true, nillable = true)
    protected String telefonoCasa;
    @XmlElement(name = "telefono_lavoro", required = true, nillable = true)
    protected String telefonoLavoro;
    @XmlElement(name = "telefono_cellulare", required = true, nillable = true)
    protected String telefonoCellulare;
    @XmlElement(name = "livello_condivisione_altri_operatori", required = true)
    protected String livelloCondivisioneAltriOperatori;
    @XmlElement(required = true)
    protected String disponibilita;
    @XmlElement(name = "data_inizio_disponibilita", required = true)
    protected String dataInizioDisponibilita;
    @XmlElement(name = "data_fine_disponibilita", required = true)
    protected String dataFineDisponibilita;
    @XmlElement(name = "tipologia_affido", required = true)
    protected String tipologiaAffido;
    @XmlElement(name = "modalita_affido", required = true)
    protected String modalitaAffido;
    @XmlElement(required = true, nillable = true)
    protected SiNoType gratuito;
    @XmlElement(name = "costo_mensile", required = true, nillable = true)
    protected ImportoType costoMensile;
    @XmlElement(name = "numero_figli_famiglia", required = true, nillable = true)
    protected String numeroFigliFamiglia;
    @XmlElement(name = "eta_media_figli_famiglia", required = true, nillable = true)
    protected String etaMediaFigliFamiglia;
    @XmlElement(name = "posti_disponibili", required = true, nillable = true)
    protected String postiDisponibili;
    @XmlElement(name = "campo_note", required = true, nillable = true)
    protected String campoNote;
    @XmlElement(name = "codice_fiscale_operatore_riferimento", required = true)
    protected String codiceFiscaleOperatoreRiferimento;

    /**
     * Gets the value of the codiceIndividualeAnagrafeComunale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceIndividualeAnagrafeComunale() {
        return codiceIndividualeAnagrafeComunale;
    }

    /**
     * Sets the value of the codiceIndividualeAnagrafeComunale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceIndividualeAnagrafeComunale(String value) {
        this.codiceIndividualeAnagrafeComunale = value;
    }

    /**
     * Gets the value of the codiceNucleoFamiliareAnagrafeComunale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceNucleoFamiliareAnagrafeComunale() {
        return codiceNucleoFamiliareAnagrafeComunale;
    }

    /**
     * Sets the value of the codiceNucleoFamiliareAnagrafeComunale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceNucleoFamiliareAnagrafeComunale(String value) {
        this.codiceNucleoFamiliareAnagrafeComunale = value;
    }

    /**
     * Gets the value of the cognome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * Sets the value of the cognome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCognome(String value) {
        this.cognome = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the dataNascita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataNascita() {
        return dataNascita;
    }

    /**
     * Sets the value of the dataNascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataNascita(String value) {
        this.dataNascita = value;
    }

    /**
     * Gets the value of the sesso property.
     * 
     * @return
     *     possible object is
     *     {@link SessoType }
     *     
     */
    public SessoType getSesso() {
        return sesso;
    }

    /**
     * Sets the value of the sesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessoType }
     *     
     */
    public void setSesso(SessoType value) {
        this.sesso = value;
    }

    /**
     * Gets the value of the informazioniTerritorialiNascita property.
     * 
     * @return
     *     possible object is
     *     {@link InformazioniTerritorialiType }
     *     
     */
    public InformazioniTerritorialiType getInformazioniTerritorialiNascita() {
        return informazioniTerritorialiNascita;
    }

    /**
     * Sets the value of the informazioniTerritorialiNascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformazioniTerritorialiType }
     *     
     */
    public void setInformazioniTerritorialiNascita(InformazioniTerritorialiType value) {
        this.informazioniTerritorialiNascita = value;
    }

    /**
     * Gets the value of the cittadinanza property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cittadinanza property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCittadinanza().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatoType }
     * 
     * 
     */
    public List<StatoType> getCittadinanza() {
        if (cittadinanza == null) {
            cittadinanza = new ArrayList<StatoType>();
        }
        return this.cittadinanza;
    }

    /**
     * Gets the value of the codiceFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    /**
     * Sets the value of the codiceFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscale(String value) {
        this.codiceFiscale = value;
    }

    /**
     * Gets the value of the statoCivile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatoCivile() {
        return statoCivile;
    }

    /**
     * Sets the value of the statoCivile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatoCivile(String value) {
        this.statoCivile = value;
    }

    /**
     * Gets the value of the comuneResidenza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComuneResidenza() {
        return comuneResidenza;
    }

    /**
     * Sets the value of the comuneResidenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComuneResidenza(String value) {
        this.comuneResidenza = value;
    }

    /**
     * Gets the value of the indirizzoResidenza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndirizzoResidenza() {
        return indirizzoResidenza;
    }

    /**
     * Sets the value of the indirizzoResidenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndirizzoResidenza(String value) {
        this.indirizzoResidenza = value;
    }

    /**
     * Gets the value of the telefonoCasa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefonoCasa() {
        return telefonoCasa;
    }

    /**
     * Sets the value of the telefonoCasa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefonoCasa(String value) {
        this.telefonoCasa = value;
    }

    /**
     * Gets the value of the telefonoLavoro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefonoLavoro() {
        return telefonoLavoro;
    }

    /**
     * Sets the value of the telefonoLavoro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefonoLavoro(String value) {
        this.telefonoLavoro = value;
    }

    /**
     * Gets the value of the telefonoCellulare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefonoCellulare() {
        return telefonoCellulare;
    }

    /**
     * Sets the value of the telefonoCellulare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefonoCellulare(String value) {
        this.telefonoCellulare = value;
    }

    /**
     * Gets the value of the livelloCondivisioneAltriOperatori property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLivelloCondivisioneAltriOperatori() {
        return livelloCondivisioneAltriOperatori;
    }

    /**
     * Sets the value of the livelloCondivisioneAltriOperatori property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLivelloCondivisioneAltriOperatori(String value) {
        this.livelloCondivisioneAltriOperatori = value;
    }

    /**
     * Gets the value of the disponibilita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisponibilita() {
        return disponibilita;
    }

    /**
     * Sets the value of the disponibilita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisponibilita(String value) {
        this.disponibilita = value;
    }

    /**
     * Gets the value of the dataInizioDisponibilita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataInizioDisponibilita() {
        return dataInizioDisponibilita;
    }

    /**
     * Sets the value of the dataInizioDisponibilita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataInizioDisponibilita(String value) {
        this.dataInizioDisponibilita = value;
    }

    /**
     * Gets the value of the dataFineDisponibilita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFineDisponibilita() {
        return dataFineDisponibilita;
    }

    /**
     * Sets the value of the dataFineDisponibilita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFineDisponibilita(String value) {
        this.dataFineDisponibilita = value;
    }

    /**
     * Gets the value of the tipologiaAffido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipologiaAffido() {
        return tipologiaAffido;
    }

    /**
     * Sets the value of the tipologiaAffido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipologiaAffido(String value) {
        this.tipologiaAffido = value;
    }

    /**
     * Gets the value of the modalitaAffido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModalitaAffido() {
        return modalitaAffido;
    }

    /**
     * Sets the value of the modalitaAffido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModalitaAffido(String value) {
        this.modalitaAffido = value;
    }

    /**
     * Gets the value of the gratuito property.
     * 
     * @return
     *     possible object is
     *     {@link SiNoType }
     *     
     */
    public SiNoType getGratuito() {
        return gratuito;
    }

    /**
     * Sets the value of the gratuito property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiNoType }
     *     
     */
    public void setGratuito(SiNoType value) {
        this.gratuito = value;
    }

    /**
     * Gets the value of the costoMensile property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getCostoMensile() {
        return costoMensile;
    }

    /**
     * Sets the value of the costoMensile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setCostoMensile(ImportoType value) {
        this.costoMensile = value;
    }

    /**
     * Gets the value of the numeroFigliFamiglia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroFigliFamiglia() {
        return numeroFigliFamiglia;
    }

    /**
     * Sets the value of the numeroFigliFamiglia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroFigliFamiglia(String value) {
        this.numeroFigliFamiglia = value;
    }

    /**
     * Gets the value of the etaMediaFigliFamiglia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEtaMediaFigliFamiglia() {
        return etaMediaFigliFamiglia;
    }

    /**
     * Sets the value of the etaMediaFigliFamiglia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEtaMediaFigliFamiglia(String value) {
        this.etaMediaFigliFamiglia = value;
    }

    /**
     * Gets the value of the postiDisponibili property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostiDisponibili() {
        return postiDisponibili;
    }

    /**
     * Sets the value of the postiDisponibili property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostiDisponibili(String value) {
        this.postiDisponibili = value;
    }

    /**
     * Gets the value of the campoNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampoNote() {
        return campoNote;
    }

    /**
     * Sets the value of the campoNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampoNote(String value) {
        this.campoNote = value;
    }

    /**
     * Gets the value of the codiceFiscaleOperatoreRiferimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscaleOperatoreRiferimento() {
        return codiceFiscaleOperatoreRiferimento;
    }

    /**
     * Sets the value of the codiceFiscaleOperatoreRiferimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscaleOperatoreRiferimento(String value) {
        this.codiceFiscaleOperatoreRiferimento = value;
    }

}
