//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for importo_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="importo_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="importo_parte_intera">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *               &lt;pattern value="[0-9]{1,5}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="importo_parte_decimale">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *               &lt;pattern value="[0-9]{1,2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "importo_type", propOrder = {
    "importoParteIntera",
    "importoParteDecimale"
})
public class ImportoType {

    @XmlElement(name = "importo_parte_intera", required = true)
    protected String importoParteIntera;
    @XmlElement(name = "importo_parte_decimale", required = true)
    protected String importoParteDecimale;

    /**
     * Gets the value of the importoParteIntera property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportoParteIntera() {
        return importoParteIntera;
    }

    /**
     * Sets the value of the importoParteIntera property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportoParteIntera(String value) {
        this.importoParteIntera = value;
    }

    /**
     * Gets the value of the importoParteDecimale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportoParteDecimale() {
        return importoParteDecimale;
    }

    /**
     * Sets the value of the importoParteDecimale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportoParteDecimale(String value) {
        this.importoParteDecimale = value;
    }

}
