//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for informazioni_territoriali_italiane_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="informazioni_territoriali_italiane_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stato_nascita" type="{}stato_italia_type"/>
 *         &lt;element name="comune_italiano_nascita" type="{}comune_italiano_type"/>
 *         &lt;element name="comune_straniero_nascita" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "informazioni_territoriali_italiane_type", propOrder = {
    "statoNascita",
    "comuneItalianoNascita",
    "comuneStranieroNascita"
})
public class InformazioniTerritorialiItalianeType {

    @XmlElement(name = "stato_nascita", required = true)
    protected String statoNascita;
    @XmlElement(name = "comune_italiano_nascita", required = true)
    protected String comuneItalianoNascita;
    @XmlElement(name = "comune_straniero_nascita", required = true)
    protected Object comuneStranieroNascita;

    /**
     * Gets the value of the statoNascita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatoNascita() {
        return statoNascita;
    }

    /**
     * Sets the value of the statoNascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatoNascita(String value) {
        this.statoNascita = value;
    }

    /**
     * Gets the value of the comuneItalianoNascita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComuneItalianoNascita() {
        return comuneItalianoNascita;
    }

    /**
     * Sets the value of the comuneItalianoNascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComuneItalianoNascita(String value) {
        this.comuneItalianoNascita = value;
    }

    /**
     * Gets the value of the comuneStranieroNascita property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getComuneStranieroNascita() {
        return comuneStranieroNascita;
    }

    /**
     * Sets the value of the comuneStranieroNascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setComuneStranieroNascita(Object value) {
        this.comuneStranieroNascita = value;
    }

}
