//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for informazioni_territoriali_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="informazioni_territoriali_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="informazioni_territoriali_italiane" type="{}informazioni_territoriali_italiane_type"/>
 *         &lt;element name="informazioni_territoriali_non_italiane" type="{}informazioni_territoriali_non_taliane_type"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "informazioni_territoriali_type", propOrder = {
    "informazioniTerritorialiItaliane",
    "informazioniTerritorialiNonItaliane"
})
public class InformazioniTerritorialiType {

    @XmlElement(name = "informazioni_territoriali_italiane")
    protected InformazioniTerritorialiItalianeType informazioniTerritorialiItaliane;
    @XmlElement(name = "informazioni_territoriali_non_italiane")
    protected InformazioniTerritorialiNonTalianeType informazioniTerritorialiNonItaliane;

    /**
     * Gets the value of the informazioniTerritorialiItaliane property.
     * 
     * @return
     *     possible object is
     *     {@link InformazioniTerritorialiItalianeType }
     *     
     */
    public InformazioniTerritorialiItalianeType getInformazioniTerritorialiItaliane() {
        return informazioniTerritorialiItaliane;
    }

    /**
     * Sets the value of the informazioniTerritorialiItaliane property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformazioniTerritorialiItalianeType }
     *     
     */
    public void setInformazioniTerritorialiItaliane(InformazioniTerritorialiItalianeType value) {
        this.informazioniTerritorialiItaliane = value;
    }

    /**
     * Gets the value of the informazioniTerritorialiNonItaliane property.
     * 
     * @return
     *     possible object is
     *     {@link InformazioniTerritorialiNonTalianeType }
     *     
     */
    public InformazioniTerritorialiNonTalianeType getInformazioniTerritorialiNonItaliane() {
        return informazioniTerritorialiNonItaliane;
    }

    /**
     * Sets the value of the informazioniTerritorialiNonItaliane property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformazioniTerritorialiNonTalianeType }
     *     
     */
    public void setInformazioniTerritorialiNonItaliane(InformazioniTerritorialiNonTalianeType value) {
        this.informazioniTerritorialiNonItaliane = value;
    }

}
