//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for intervento_non_pai_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="intervento_non_pai_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="da0100"/>
 *     &lt;enumeration value="da0200"/>
 *     &lt;enumeration value="da0500"/>
 *     &lt;enumeration value="da0600"/>
 *     &lt;enumeration value="da0800"/>
 *     &lt;enumeration value="da0900"/>
 *     &lt;enumeration value="da1100"/>
 *     &lt;enumeration value="da1200"/>
 *     &lt;enumeration value="da1400"/>
 *     &lt;enumeration value="da1500"/>
 *     &lt;enumeration value="da1600"/>
 *     &lt;enumeration value="da1700"/>
 *     &lt;enumeration value="da1800"/>
 *     &lt;enumeration value="da1900"/>
 *     &lt;enumeration value="da2000"/>
 *     &lt;enumeration value="dc0600"/>
 *     &lt;enumeration value="dd1200"/>
 *     &lt;enumeration value="dd1700"/>
 *     &lt;enumeration value="dfB100"/>
 *     &lt;enumeration value="dfB400"/>
 *     &lt;enumeration value="dgA100"/>
 *     &lt;enumeration value="dgA200"/>
 *     &lt;enumeration value="dgA300"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "intervento_non_pai_type")
@XmlEnum
public enum InterventoNonPaiType {

    @XmlEnumValue("da0100")
    DA_0100("da0100"),
    @XmlEnumValue("da0200")
    DA_0200("da0200"),
    @XmlEnumValue("da0500")
    DA_0500("da0500"),
    @XmlEnumValue("da0600")
    DA_0600("da0600"),
    @XmlEnumValue("da0800")
    DA_0800("da0800"),
    @XmlEnumValue("da0900")
    DA_0900("da0900"),
    @XmlEnumValue("da1100")
    DA_1100("da1100"),
    @XmlEnumValue("da1200")
    DA_1200("da1200"),
    @XmlEnumValue("da1400")
    DA_1400("da1400"),
    @XmlEnumValue("da1500")
    DA_1500("da1500"),
    @XmlEnumValue("da1600")
    DA_1600("da1600"),
    @XmlEnumValue("da1700")
    DA_1700("da1700"),
    @XmlEnumValue("da1800")
    DA_1800("da1800"),
    @XmlEnumValue("da1900")
    DA_1900("da1900"),
    @XmlEnumValue("da2000")
    DA_2000("da2000"),
    @XmlEnumValue("dc0600")
    DC_0600("dc0600"),
    @XmlEnumValue("dd1200")
    DD_1200("dd1200"),
    @XmlEnumValue("dd1700")
    DD_1700("dd1700"),
    @XmlEnumValue("dfB100")
    DF_B_100("dfB100"),
    @XmlEnumValue("dfB400")
    DF_B_400("dfB400"),
    @XmlEnumValue("dgA100")
    DG_A_100("dgA100"),
    @XmlEnumValue("dgA200")
    DG_A_200("dgA200"),
    @XmlEnumValue("dgA300")
    DG_A_300("dgA300");
    private final String value;

    InterventoNonPaiType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InterventoNonPaiType fromValue(String v) {
        for (InterventoNonPaiType c: InterventoNonPaiType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
