//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for motivo_chiusura_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="motivo_chiusura_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="F01"/>
 *     &lt;enumeration value="F02"/>
 *     &lt;enumeration value="F03"/>
 *     &lt;enumeration value="F04"/>
 *     &lt;enumeration value="F06"/>
 *     &lt;enumeration value="F11"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "motivo_chiusura_type")
@XmlEnum
public enum MotivoChiusuraType {

    @XmlEnumValue("F01")
    F_01("F01"),
    @XmlEnumValue("F02")
    F_02("F02"),
    @XmlEnumValue("F03")
    F_03("F03"),
    @XmlEnumValue("F04")
    F_04("F04"),
    @XmlEnumValue("F06")
    F_06("F06"),
    @XmlEnumValue("F11")
    F_11("F11");
    private final String value;

    MotivoChiusuraType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MotivoChiusuraType fromValue(String v) {
        for (MotivoChiusuraType c: MotivoChiusuraType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
