//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.wego.welfarego.xml.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.wego.welfarego.xml.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.AnagraficaUtente }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.AnagraficaUtente createElencoCartelleSocialiCartellaSocialeAnagraficaUtente() {
        return new ElencoCartelleSociali.CartellaSociale.AnagraficaUtente();
    }

    /**
     * Create an instance of {@link SchedulazioneSadType.Tempo }
     * 
     */
    public SchedulazioneSadType.Tempo createSchedulazioneSadTypeTempo() {
        return new SchedulazioneSadType.Tempo();
    }

    /**
     * Create an instance of {@link SchedulazioneSadType.Tempo.OreNonNulle }
     * 
     */
    public SchedulazioneSadType.Tempo.OreNonNulle createSchedulazioneSadTypeTempoOreNonNulle() {
        return new SchedulazioneSadType.Tempo.OreNonNulle();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali }
     * 
     */
    public ElencoCartelleSociali createElencoCartelleSociali() {
        return new ElencoCartelleSociali();
    }

    /**
     * Create an instance of {@link StatoType }
     * 
     */
    public StatoType createStatoType() {
        return new StatoType();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.FondoPerPoverta }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.FondoPerPoverta createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoFondoPerPoverta() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.FondoPerPoverta();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoResidenziale() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01 .SoggettiCoinvolti }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01 .SoggettiCoinvolti createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoRedditoDiBaseDettaglio01SoggettiCoinvolti() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01 .SoggettiCoinvolti();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoComunitaMadreBambino }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoComunitaMadreBambino createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoResidenzialeInterventoComunitaMadreBambino() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoComunitaMadreBambino();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaIntervento() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi createElencoCartelleSocialiCartellaSocialePaiElencoInterventi() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzaProtetta }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzaProtetta createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoResidenzialeInterventoResidenzaProtetta() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzaProtetta();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzialeSenzaStruttura }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzialeSenzaStruttura createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoResidenzialeInterventoResidenzialeSenzaStruttura() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzialeSenzaStruttura();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale createElencoCartelleSocialiCartellaSociale() {
        return new ElencoCartelleSociali.CartellaSociale();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoRedditoDiBase() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase();
    }

    /**
     * Create an instance of {@link AssistenteSocialeType }
     * 
     */
    public AssistenteSocialeType createAssistenteSocialeType() {
        return new AssistenteSocialeType();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.FondoAutonomiaPossibile }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.FondoAutonomiaPossibile createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoFondoAutonomiaPossibile() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.FondoAutonomiaPossibile();
    }

    /**
     * Create an instance of {@link InformazioniTerritorialiItalianeType }
     * 
     */
    public InformazioniTerritorialiItalianeType createInformazioniTerritorialiItalianeType() {
        return new InformazioniTerritorialiItalianeType();
    }

    /**
     * Create an instance of {@link ImportoType }
     * 
     */
    public ImportoType createImportoType() {
        return new ImportoType();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.ElencoPersoneRiferimento.PersonaRiferimento }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.ElencoPersoneRiferimento.PersonaRiferimento createElencoCartelleSocialiCartellaSocialeElencoPersoneRiferimentoPersonaRiferimento() {
        return new ElencoCartelleSociali.CartellaSociale.ElencoPersoneRiferimento.PersonaRiferimento();
    }

    /**
     * Create an instance of {@link MacroTipologiaSadType }
     * 
     */
    public MacroTipologiaSadType createMacroTipologiaSadType() {
        return new MacroTipologiaSadType();
    }

    /**
     * Create an instance of {@link SchedulazioneSadType.Tempo.MinutiNonNulli }
     * 
     */
    public SchedulazioneSadType.Tempo.MinutiNonNulli createSchedulazioneSadTypeTempoMinutiNonNulli() {
        return new SchedulazioneSadType.Tempo.MinutiNonNulli();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzaPolifunzionaleModuliFasciaA }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzaPolifunzionaleModuliFasciaA createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoResidenzialeInterventoResidenzaPolifunzionaleModuliFasciaA() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzaPolifunzionaleModuliFasciaA();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.Profilo }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.Profilo createElencoCartelleSocialiCartellaSocialePaiProfilo() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.Profilo();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01 .EsitoValutazioneObiettiviPatto }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01 .EsitoValutazioneObiettiviPatto createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoRedditoDiBaseDettaglio01EsitoValutazioneObiettiviPatto() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01 .EsitoValutazioneObiettiviPatto();
    }

    /**
     * Create an instance of {@link SchedulazioneSadType.Tempo.OreMinutiNonNulli }
     * 
     */
    public SchedulazioneSadType.Tempo.OreMinutiNonNulli createSchedulazioneSadTypeTempoOreMinutiNonNulli() {
        return new SchedulazioneSadType.Tempo.OreMinutiNonNulli();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoComunitaAlloggio }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoComunitaAlloggio createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoResidenzialeInterventoComunitaAlloggio() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoComunitaAlloggio();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.FondoAutonomiaPossibile.Dettaglio02 }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.FondoAutonomiaPossibile.Dettaglio02 createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoFondoAutonomiaPossibileDettaglio02() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.FondoAutonomiaPossibile.Dettaglio02();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01 }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01 createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoRedditoDiBaseDettaglio01() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01();
    }

    /**
     * Create an instance of {@link FamigliaAffidatariaType }
     * 
     */
    public FamigliaAffidatariaType createFamigliaAffidatariaType() {
        return new FamigliaAffidatariaType();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.NonPai }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.NonPai createElencoCartelleSocialiCartellaSocialeNonPai() {
        return new ElencoCartelleSociali.CartellaSociale.NonPai();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.ElencoPersoneRiferimento }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.ElencoPersoneRiferimento createElencoCartelleSocialiCartellaSocialeElencoPersoneRiferimento() {
        return new ElencoCartelleSociali.CartellaSociale.ElencoPersoneRiferimento();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai createElencoCartelleSocialiCartellaSocialePai() {
        return new ElencoCartelleSociali.CartellaSociale.Pai();
    }

    /**
     * Create an instance of {@link SchedulazioneSadType }
     * 
     */
    public SchedulazioneSadType createSchedulazioneSadType() {
        return new SchedulazioneSadType();
    }

    /**
     * Create an instance of {@link ElencoAssistentiSociali }
     * 
     */
    public ElencoAssistentiSociali createElencoAssistentiSociali() {
        return new ElencoAssistentiSociali();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.DiagnosiEObiettivi }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.DiagnosiEObiettivi createElencoCartelleSocialiCartellaSocialePaiDiagnosiEObiettivi() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.DiagnosiEObiettivi();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoRsa }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoRsa createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoResidenzialeInterventoRsa() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoRsa();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento createElencoCartelleSocialiCartellaSocialePaiElencoInterventiIntervento() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.NonStrutturato }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.NonStrutturato createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoNonStrutturato() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.NonStrutturato();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoCasaAlbergo }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoCasaAlbergo createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoResidenzialeInterventoCasaAlbergo() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoCasaAlbergo();
    }

    /**
     * Create an instance of {@link InformazioniTerritorialiType }
     * 
     */
    public InformazioniTerritorialiType createInformazioniTerritorialiType() {
        return new InformazioniTerritorialiType();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.NonStrutturato.Dettaglio }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.NonStrutturato.Dettaglio createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoNonStrutturatoDettaglio() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.NonStrutturato.Dettaglio();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01 .ObiettiviPatto }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01 .ObiettiviPatto createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoRedditoDiBaseDettaglio01ObiettiviPatto() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.RedditoDiBase.Dettaglio01 .ObiettiviPatto();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoUtenzaDiversificata }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoUtenzaDiversificata createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoResidenzialeInterventoUtenzaDiversificata() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoUtenzaDiversificata();
    }

    /**
     * Create an instance of {@link ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzaPolifunzionale }
     * 
     */
    public ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzaPolifunzionale createElencoCartelleSocialiCartellaSocialePaiElencoInterventiInterventoSpecificitaInterventoResidenzialeInterventoResidenzaPolifunzionale() {
        return new ElencoCartelleSociali.CartellaSociale.Pai.ElencoInterventi.Intervento.SpecificitaIntervento.Residenziale.InterventoResidenzaPolifunzionale();
    }

    /**
     * Create an instance of {@link InformazioniTerritorialiNonTalianeType }
     * 
     */
    public InformazioniTerritorialiNonTalianeType createInformazioniTerritorialiNonTalianeType() {
        return new InformazioniTerritorialiNonTalianeType();
    }

}
