//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * a fronte della valorizzazione di uno dei suoi elementi, devono essere valorizzati anche tutti gli altri
 * 
 * <p>Java class for schedulazione_sad_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="schedulazione_sad_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="arco_temporale" type="{}arco_temporale_type"/>
 *         &lt;element name="frequenza">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numero_volte">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="erogatore" type="{}erogatore_type"/>
 *         &lt;element name="campo_note">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tempo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="minuti_non_nulli">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="totale_ore" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="totale_minuti">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                   &lt;minInclusive value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ore_non_nulle">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="totale_ore">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                   &lt;minInclusive value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="totale_minuti" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ore_minuti_non_nulli">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="totale_ore">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                   &lt;minInclusive value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="totale_minuti">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                   &lt;minInclusive value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "schedulazione_sad_type", propOrder = {
    "arcoTemporale",
    "frequenza",
    "numeroVolte",
    "erogatore",
    "campoNote",
    "tempo"
})
public class SchedulazioneSadType {

    @XmlElement(name = "arco_temporale", required = true)
    protected String arcoTemporale;
    @XmlElement(required = true)
    protected BigInteger frequenza;
    @XmlElement(name = "numero_volte", required = true)
    protected BigInteger numeroVolte;
    @XmlElement(required = true)
    protected String erogatore;
    @XmlElement(name = "campo_note", required = true)
    protected String campoNote;
    @XmlElement(required = true)
    protected SchedulazioneSadType.Tempo tempo;

    /**
     * Gets the value of the arcoTemporale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArcoTemporale() {
        return arcoTemporale;
    }

    /**
     * Sets the value of the arcoTemporale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArcoTemporale(String value) {
        this.arcoTemporale = value;
    }

    /**
     * Gets the value of the frequenza property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFrequenza() {
        return frequenza;
    }

    /**
     * Sets the value of the frequenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFrequenza(BigInteger value) {
        this.frequenza = value;
    }

    /**
     * Gets the value of the numeroVolte property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumeroVolte() {
        return numeroVolte;
    }

    /**
     * Sets the value of the numeroVolte property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumeroVolte(BigInteger value) {
        this.numeroVolte = value;
    }

    /**
     * Gets the value of the erogatore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErogatore() {
        return erogatore;
    }

    /**
     * Sets the value of the erogatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErogatore(String value) {
        this.erogatore = value;
    }

    /**
     * Gets the value of the campoNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampoNote() {
        return campoNote;
    }

    /**
     * Sets the value of the campoNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampoNote(String value) {
        this.campoNote = value;
    }

    /**
     * Gets the value of the tempo property.
     * 
     * @return
     *     possible object is
     *     {@link SchedulazioneSadType.Tempo }
     *     
     */
    public SchedulazioneSadType.Tempo getTempo() {
        return tempo;
    }

    /**
     * Sets the value of the tempo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedulazioneSadType.Tempo }
     *     
     */
    public void setTempo(SchedulazioneSadType.Tempo value) {
        this.tempo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="minuti_non_nulli">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="totale_ore" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="totale_minuti">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                         &lt;minInclusive value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ore_non_nulle">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="totale_ore">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                         &lt;minInclusive value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="totale_minuti" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ore_minuti_non_nulli">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="totale_ore">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                         &lt;minInclusive value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="totale_minuti">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                         &lt;minInclusive value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "minutiNonNulli",
        "oreNonNulle",
        "oreMinutiNonNulli"
    })
    public static class Tempo {

        @XmlElement(name = "minuti_non_nulli")
        protected SchedulazioneSadType.Tempo.MinutiNonNulli minutiNonNulli;
        @XmlElement(name = "ore_non_nulle")
        protected SchedulazioneSadType.Tempo.OreNonNulle oreNonNulle;
        @XmlElement(name = "ore_minuti_non_nulli")
        protected SchedulazioneSadType.Tempo.OreMinutiNonNulli oreMinutiNonNulli;

        /**
         * Gets the value of the minutiNonNulli property.
         * 
         * @return
         *     possible object is
         *     {@link SchedulazioneSadType.Tempo.MinutiNonNulli }
         *     
         */
        public SchedulazioneSadType.Tempo.MinutiNonNulli getMinutiNonNulli() {
            return minutiNonNulli;
        }

        /**
         * Sets the value of the minutiNonNulli property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchedulazioneSadType.Tempo.MinutiNonNulli }
         *     
         */
        public void setMinutiNonNulli(SchedulazioneSadType.Tempo.MinutiNonNulli value) {
            this.minutiNonNulli = value;
        }

        /**
         * Gets the value of the oreNonNulle property.
         * 
         * @return
         *     possible object is
         *     {@link SchedulazioneSadType.Tempo.OreNonNulle }
         *     
         */
        public SchedulazioneSadType.Tempo.OreNonNulle getOreNonNulle() {
            return oreNonNulle;
        }

        /**
         * Sets the value of the oreNonNulle property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchedulazioneSadType.Tempo.OreNonNulle }
         *     
         */
        public void setOreNonNulle(SchedulazioneSadType.Tempo.OreNonNulle value) {
            this.oreNonNulle = value;
        }

        /**
         * Gets the value of the oreMinutiNonNulli property.
         * 
         * @return
         *     possible object is
         *     {@link SchedulazioneSadType.Tempo.OreMinutiNonNulli }
         *     
         */
        public SchedulazioneSadType.Tempo.OreMinutiNonNulli getOreMinutiNonNulli() {
            return oreMinutiNonNulli;
        }

        /**
         * Sets the value of the oreMinutiNonNulli property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchedulazioneSadType.Tempo.OreMinutiNonNulli }
         *     
         */
        public void setOreMinutiNonNulli(SchedulazioneSadType.Tempo.OreMinutiNonNulli value) {
            this.oreMinutiNonNulli = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="totale_ore" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="totale_minuti">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;minInclusive value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "totaleOre",
            "totaleMinuti"
        })
        public static class MinutiNonNulli {

            @XmlElement(name = "totale_ore", required = true, nillable = true)
            protected Object totaleOre;
            @XmlElement(name = "totale_minuti", required = true)
            protected BigInteger totaleMinuti;

            /**
             * Gets the value of the totaleOre property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getTotaleOre() {
                return totaleOre;
            }

            /**
             * Sets the value of the totaleOre property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setTotaleOre(Object value) {
                this.totaleOre = value;
            }

            /**
             * Gets the value of the totaleMinuti property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTotaleMinuti() {
                return totaleMinuti;
            }

            /**
             * Sets the value of the totaleMinuti property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTotaleMinuti(BigInteger value) {
                this.totaleMinuti = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="totale_ore">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;minInclusive value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="totale_minuti">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;minInclusive value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "totaleOre",
            "totaleMinuti"
        })
        public static class OreMinutiNonNulli {

            @XmlElement(name = "totale_ore", required = true)
            protected BigInteger totaleOre;
            @XmlElement(name = "totale_minuti", required = true)
            protected BigInteger totaleMinuti;

            /**
             * Gets the value of the totaleOre property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTotaleOre() {
                return totaleOre;
            }

            /**
             * Sets the value of the totaleOre property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTotaleOre(BigInteger value) {
                this.totaleOre = value;
            }

            /**
             * Gets the value of the totaleMinuti property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTotaleMinuti() {
                return totaleMinuti;
            }

            /**
             * Sets the value of the totaleMinuti property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTotaleMinuti(BigInteger value) {
                this.totaleMinuti = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="totale_ore">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;minInclusive value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="totale_minuti" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "totaleOre",
            "totaleMinuti"
        })
        public static class OreNonNulle {

            @XmlElement(name = "totale_ore", required = true)
            protected BigInteger totaleOre;
            @XmlElement(name = "totale_minuti", required = true, nillable = true)
            protected Object totaleMinuti;

            /**
             * Gets the value of the totaleOre property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTotaleOre() {
                return totaleOre;
            }

            /**
             * Sets the value of the totaleOre property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTotaleOre(BigInteger value) {
                this.totaleOre = value;
            }

            /**
             * Gets the value of the totaleMinuti property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getTotaleMinuti() {
                return totaleMinuti;
            }

            /**
             * Sets the value of the totaleMinuti property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setTotaleMinuti(Object value) {
                this.totaleMinuti = value;
            }

        }

    }

}
