//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stato_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stato_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="stato_italiano" type="{}stato_italia_type"/>
 *         &lt;element name="stato_non_italiano" type="{}stato_non_italia_type"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stato_type", propOrder = {
    "statoItaliano",
    "statoNonItaliano"
})
public class StatoType {

    @XmlElement(name = "stato_italiano")
    protected String statoItaliano;
    @XmlElement(name = "stato_non_italiano")
    protected String statoNonItaliano;

    /**
     * Gets the value of the statoItaliano property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatoItaliano() {
        return statoItaliano;
    }

    /**
     * Sets the value of the statoItaliano property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatoItaliano(String value) {
        this.statoItaliano = value;
    }

    /**
     * Gets the value of the statoNonItaliano property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatoNonItaliano() {
        return statoNonItaliano;
    }

    /**
     * Sets the value of the statoNonItaliano property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatoNonItaliano(String value) {
        this.statoNonItaliano = value;
    }

}
