//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipo_intervento_residenziale_maggiorenne_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tipo_intervento_residenziale_maggiorenne_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="de0800"/>
 *     &lt;enumeration value="de0900"/>
 *     &lt;enumeration value="de1000"/>
 *     &lt;enumeration value="de1100"/>
 *     &lt;enumeration value="de1200"/>
 *     &lt;enumeration value="de1300"/>
 *     &lt;enumeration value="de1400"/>
 *     &lt;enumeration value="de1500"/>
 *     &lt;enumeration value="de1600"/>
 *     &lt;enumeration value="de1700"/>
 *     &lt;enumeration value="de1800"/>
 *     &lt;enumeration value="de1900"/>
 *     &lt;enumeration value="de2000"/>
 *     &lt;enumeration value="de2100"/>
 *     &lt;enumeration value="de2200"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tipo_intervento_residenziale_maggiorenne_type")
@XmlEnum
public enum TipoInterventoResidenzialeMaggiorenneType {

    @XmlEnumValue("de0800")
    DE_0800("de0800"),
    @XmlEnumValue("de0900")
    DE_0900("de0900"),
    @XmlEnumValue("de1000")
    DE_1000("de1000"),
    @XmlEnumValue("de1100")
    DE_1100("de1100"),
    @XmlEnumValue("de1200")
    DE_1200("de1200"),
    @XmlEnumValue("de1300")
    DE_1300("de1300"),
    @XmlEnumValue("de1400")
    DE_1400("de1400"),
    @XmlEnumValue("de1500")
    DE_1500("de1500"),
    @XmlEnumValue("de1600")
    DE_1600("de1600"),
    @XmlEnumValue("de1700")
    DE_1700("de1700"),
    @XmlEnumValue("de1800")
    DE_1800("de1800"),
    @XmlEnumValue("de1900")
    DE_1900("de1900"),
    @XmlEnumValue("de2000")
    DE_2000("de2000"),
    @XmlEnumValue("de2100")
    DE_2100("de2100"),
    @XmlEnumValue("de2200")
    DE_2200("de2200");
    private final String value;

    TipoInterventoResidenzialeMaggiorenneType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipoInterventoResidenzialeMaggiorenneType fromValue(String v) {
        for (TipoInterventoResidenzialeMaggiorenneType c: TipoInterventoResidenzialeMaggiorenneType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
