//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipologia_utente_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tipologia_utente_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A01"/>
 *     &lt;enumeration value="A02"/>
 *     &lt;enumeration value="A03"/>
 *     &lt;enumeration value="A04"/>
 *     &lt;enumeration value="A05"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tipologia_utente_type")
@XmlEnum
public enum TipologiaUtenteType {

    @XmlEnumValue("A01")
    A_01("A01"),
    @XmlEnumValue("A02")
    A_02("A02"),
    @XmlEnumValue("A03")
    A_03("A03"),
    @XmlEnumValue("A04")
    A_04("A04"),
    @XmlEnumValue("A05")
    A_05("A05");
    private final String value;

    TipologiaUtenteType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipologiaUtenteType fromValue(String v) {
        for (TipologiaUtenteType c: TipologiaUtenteType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
