//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 06:46:27 PM CEST 
//


package it.wego.welfarego.xsd.cartellasociale;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipologia_presa_carico_pregressa_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tipologia_presa_carico_pregressa_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="db"/>
 *     &lt;enumeration value="df"/>
 *     &lt;enumeration value="da"/>
 *     &lt;enumeration value="dc"/>
 *     &lt;enumeration value="dg"/>
 *     &lt;enumeration value="de"/>
 *     &lt;enumeration value="dd"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tipologia_presa_carico_pregressa_type")
@XmlEnum
public enum TipologiaPresaCaricoPregressaType {

    @XmlEnumValue("db")
    DB("db"),
    @XmlEnumValue("df")
    DF("df"),
    @XmlEnumValue("da")
    DA("da"),
    @XmlEnumValue("dc")
    DC("dc"),
    @XmlEnumValue("dg")
    DG("dg"),
    @XmlEnumValue("de")
    DE("de"),
    @XmlEnumValue("dd")
    DD("dd");
    private final String value;

    TipologiaPresaCaricoPregressaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipologiaPresaCaricoPregressaType fromValue(String v) {
        for (TipologiaPresaCaricoPregressaType c: TipologiaPresaCaricoPregressaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
