
package it.wego.welfarego.cartellasocialews.beans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Cartella", targetNamespace = "http://insiel.it/sanita/cartellasociale/cartellaws/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Cartella {


    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaCartella
     */
    @WebMethod
    @WebResult(name = "RicevutaCartella", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaCartella inserimentoCartella(
        @WebParam(name = "InserimentoCartellaSociale", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        InserimentoCartellaSociale request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaIntervento
     */
    @WebMethod
    @WebResult(name = "RicevutaIntervento", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaIntervento inserimentoIntervento(
        @WebParam(name = "InserimentoIntervento", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        InserimentoIntervento request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaDiario
     */
    @WebMethod
    @WebResult(name = "RicevutaDiario", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaDiario inserimentoDiario(
        @WebParam(name = "InserimentoDiario", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        InserimentoDiario request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaPersonaRiferimento
     */
    @WebMethod
    @WebResult(name = "RicevutaPersonaRiferimento", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaPersonaRiferimento inserimentoPersonaRiferimento(
        @WebParam(name = "InserimentoPersonaRiferimento", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        InserimentoPersonaRiferimento request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaModificaAnagrafica
     */
    @WebMethod
    @WebResult(name = "RicevutaModificaAnagrafica", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaModificaAnagrafica modificaAnagrafica(
        @WebParam(name = "ModificaAnagrafica", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        ModificaAnagrafica request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaModificaProfilo
     */
    @WebMethod
    @WebResult(name = "RicevutaModificaProfilo", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaModificaProfilo modificaProfilo(
        @WebParam(name = "ModificaProfilo", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        ModificaProfilo request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaModificaProgetto
     */
    @WebMethod
    @WebResult(name = "RicevutaModificaProgetto", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaModificaProgetto modificaProgetto(
        @WebParam(name = "ModificaProgetto", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        ModificaProgetto request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaModificaIntervento
     */
    @WebMethod
    @WebResult(name = "RicevutaModificaIntervento", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaModificaIntervento modificaIntervento(
        @WebParam(name = "ModificaIntervento", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        ModificaIntervento request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaModificaDiario
     */
    @WebMethod
    @WebResult(name = "RicevutaModificaDiario", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaModificaDiario modificaDiario(
        @WebParam(name = "ModificaDiario", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        ModificaDiario request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaPersonaRiferimento
     */
    @WebMethod
    @WebResult(name = "RicevutaPersonaRiferimento", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaPersonaRiferimento modificaPersonaRiferimento(
        @WebParam(name = "ModificaPersonaRiferimento", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        ModificaPersonaRiferimento request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaChiudiCartella
     */
    @WebMethod
    @WebResult(name = "RicevutaChiudiCartella", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaChiudiCartella chiudiCartella(
        @WebParam(name = "ChiudiCartella", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        ChiudiCartella request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaRiattivaCartella
     */
    @WebMethod
    @WebResult(name = "RicevutaRiattivaCartella", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaRiattivaCartella riattivaCartella(
        @WebParam(name = "RiattivaCartella", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        RiattivaCartella request);

    /**
     * 
     * @param request
     * @return
     *     returns it.wego.welfarego.cartellasocialews.beans.RicevutaAzioniBackOffice
     */
    @WebMethod
    @WebResult(name = "RicevutaAzioniBackOffice", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "response")
    public RicevutaAzioniBackOffice azioniBackOffice(
        @WebParam(name = "AzioniBackOffice", targetNamespace = "http://cartellasociale.sanita.insiel.it", partName = "request")
        AzioniBackOffice request);

}
