//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 03:26:32 PM CEST 
//


package it.wego.welfarego.xsd.pratica;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatiSpecificiType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatiSpecificiType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codCampo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desCampo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codValCampo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="valCampo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiSpecificiType", propOrder = {
    "codCampo",
    "desCampo",
    "codValCampo",
    "valCampo"
})
public class DatiSpecificiType {

    @XmlElement(required = true)
    protected String codCampo;
    @XmlElement(required = true)
    protected String desCampo;
    @XmlElement(required = true)
    protected String codValCampo;
    @XmlElement(required = true)
    protected String valCampo;

    /**
     * Gets the value of the codCampo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodCampo() {
        return codCampo;
    }

    /**
     * Sets the value of the codCampo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodCampo(String value) {
        this.codCampo = value;
    }

    /**
     * Gets the value of the desCampo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesCampo() {
        return desCampo;
    }

    /**
     * Sets the value of the desCampo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesCampo(String value) {
        this.desCampo = value;
    }

    /**
     * Gets the value of the codValCampo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodValCampo() {
        return codValCampo;
    }

    /**
     * Sets the value of the codValCampo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodValCampo(String value) {
        this.codValCampo = value;
    }

    /**
     * Gets the value of the valCampo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValCampo() {
        return valCampo;
    }

    /**
     * Sets the value of the valCampo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValCampo(String value) {
        this.valCampo = value;
    }

}
