//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 03:26:32 PM CEST 
//
package it.wego.welfarego.xsd.pratica;

import it.wego.welfarego.persistence.entities.ParametriIndata;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for decodParamType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="decodParamType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codParam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desParamType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "decodParamType", propOrder = {
    "codParam",
    "desParamType"
})
public class DecodParamType {

    @XmlElement(required = true)
    protected String codParam;
    @XmlElement(required = true)
    protected String desParamType;

    public DecodParamType() {
    }

    public DecodParamType(String codParam, String desParamType) {
        this.codParam = codParam;
        this.desParamType = desParamType;
    }

    public DecodParamType(ParametriIndata parametriIndata) {
        this(parametriIndata.getIdParam().getCodParam(), parametriIndata.getDesParam());
    }

    /**
     * Gets the value of the codParam property.
     *
     * @return possible object is
     *     {@link String }
     *
     */
    public String getCodParam() {
        return codParam;
    }

    /**
     * Sets the value of the codParam property.
     *
     * @param value allowed object is
     *     {@link String }
     *
     */
    public void setCodParam(String value) {
        this.codParam = value;
    }

    /**
     * Gets the value of the desParamType property.
     *
     * @return possible object is
     *     {@link String }
     *
     */
    public String getDesParamType() {
        return desParamType;
    }

    /**
     * Sets the value of the desParamType property.
     *
     * @param value allowed object is
     *     {@link String }
     *
     */
    public void setDesParamType(String value) {
        this.desParamType = value;
    }
}
