//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 03:26:32 PM CEST 
//


package it.wego.welfarego.xsd.pratica;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for infoIndirizzoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="infoIndirizzoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cap" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codViaTs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codCivTs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desCiv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "infoIndirizzoType", propOrder = {
    "cap",
    "codViaTs",
    "desVia",
    "codCivTs",
    "desCiv"
})
public class InfoIndirizzoType {

    @XmlElement(name = "Cap", required = true)
    protected String cap;
    @XmlElement(required = true)
    protected String codViaTs;
    @XmlElement(required = true)
    protected String desVia;
    @XmlElement(required = true)
    protected String codCivTs;
    @XmlElement(required = true)
    protected String desCiv;

    /**
     * Gets the value of the cap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCap() {
        return cap;
    }

    /**
     * Sets the value of the cap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCap(String value) {
        this.cap = value;
    }

    /**
     * Gets the value of the codViaTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodViaTs() {
        return codViaTs;
    }

    /**
     * Sets the value of the codViaTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodViaTs(String value) {
        this.codViaTs = value;
    }

    /**
     * Gets the value of the desVia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesVia() {
        return desVia;
    }

    /**
     * Sets the value of the desVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesVia(String value) {
        this.desVia = value;
    }

    /**
     * Gets the value of the codCivTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodCivTs() {
        return codCivTs;
    }

    /**
     * Sets the value of the codCivTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodCivTs(String value) {
        this.codCivTs = value;
    }

    /**
     * Gets the value of the desCiv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesCiv() {
        return desCiv;
    }

    /**
     * Sets the value of the desCiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesCiv(String value) {
        this.desCiv = value;
    }

}
