//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 03:26:32 PM CEST 
//


package it.wego.welfarego.xsd.pratica;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for infoTerrType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="infoTerrType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codStato" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desStato" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codProvIta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desProvItaEst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codComIta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="desComItaEst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "infoTerrType", propOrder = {
    "codStato",
    "desStato",
    "codProvIta",
    "desProvItaEst",
    "codComIta",
    "desComItaEst"
})
public class InfoTerrType {

    @XmlElement(required = true)
    protected String codStato;
    @XmlElement(required = true)
    protected String desStato;
    @XmlElement(required = true)
    protected String codProvIta;
    @XmlElement(required = true)
    protected String desProvItaEst;
    @XmlElement(required = true)
    protected String codComIta;
    @XmlElement(required = true)
    protected String desComItaEst;

    /**
     * Gets the value of the codStato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodStato() {
        return codStato;
    }

    /**
     * Sets the value of the codStato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodStato(String value) {
        this.codStato = value;
    }

    /**
     * Gets the value of the desStato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesStato() {
        return desStato;
    }

    /**
     * Sets the value of the desStato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesStato(String value) {
        this.desStato = value;
    }

    /**
     * Gets the value of the codProvIta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodProvIta() {
        return codProvIta;
    }

    /**
     * Sets the value of the codProvIta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodProvIta(String value) {
        this.codProvIta = value;
    }

    /**
     * Gets the value of the desProvItaEst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesProvItaEst() {
        return desProvItaEst;
    }

    /**
     * Sets the value of the desProvItaEst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesProvItaEst(String value) {
        this.desProvItaEst = value;
    }

    /**
     * Gets the value of the codComIta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodComIta() {
        return codComIta;
    }

    /**
     * Sets the value of the codComIta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodComIta(String value) {
        this.codComIta = value;
    }

    /**
     * Gets the value of the desComItaEst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesComItaEst() {
        return desComItaEst;
    }

    /**
     * Sets the value of the desComItaEst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesComItaEst(String value) {
        this.desComItaEst = value;
    }

}
