//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 03:26:32 PM CEST 
//


package it.wego.welfarego.xsd.pratica;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.wego.welfarego.xsd.pratica package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.wego.welfarego.xsd.pratica
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CartellaSociale }
     * 
     */
    public CartellaSociale createCartellaSociale() {
        return new CartellaSociale();
    }

    /**
     * Create an instance of {@link DecodParamType }
     * 
     */
    public DecodParamType createDecodParamType() {
        return new DecodParamType();
    }

    /**
     * Create an instance of {@link CartellaSociale.Pai.ElencoInterventi.Intervento.ImpegnoSpesa }
     * 
     */
    public CartellaSociale.Pai.ElencoInterventi.Intervento.ImpegnoSpesa createCartellaSocialePaiElencoInterventiInterventoImpegnoSpesa() {
        return new CartellaSociale.Pai.ElencoInterventi.Intervento.ImpegnoSpesa();
    }

    /**
     * Create an instance of {@link InfoTerrType }
     * 
     */
    public InfoTerrType createInfoTerrType() {
        return new InfoTerrType();
    }

    /**
     * Create an instance of {@link DatiSpecificiType }
     * 
     */
    public DatiSpecificiType createDatiSpecificiType() {
        return new DatiSpecificiType();
    }

    /**
     * Create an instance of {@link CartellaSociale.Pai.ElencoInterventi }
     * 
     */
    public CartellaSociale.Pai.ElencoInterventi createCartellaSocialePaiElencoInterventi() {
        return new CartellaSociale.Pai.ElencoInterventi();
    }

    /**
     * Create an instance of {@link CartellaSociale.Pai.PaiAnag }
     * 
     */
    public CartellaSociale.Pai.PaiAnag createCartellaSocialePaiPaiAnag() {
        return new CartellaSociale.Pai.PaiAnag();
    }

    /**
     * Create an instance of {@link InfoIndirizzoType }
     * 
     */
    public InfoIndirizzoType createInfoIndirizzoType() {
        return new InfoIndirizzoType();
    }

    /**
     * Create an instance of {@link CartellaSociale.Pai.ElencoInterventi.Intervento }
     * 
     */
    public CartellaSociale.Pai.ElencoInterventi.Intervento createCartellaSocialePaiElencoInterventiIntervento() {
        return new CartellaSociale.Pai.ElencoInterventi.Intervento();
    }

    /**
     * Create an instance of {@link CartellaSociale.Pai }
     * 
     */
    public CartellaSociale.Pai createCartellaSocialePai() {
        return new CartellaSociale.Pai();
    }

    /**
     * Create an instance of {@link CartellaSociale.Pai.ElencoInterventi.Intervento.IntAnag }
     * 
     */
    public CartellaSociale.Pai.ElencoInterventi.Intervento.IntAnag createCartellaSocialePaiElencoInterventiInterventoIntAnag() {
        return new CartellaSociale.Pai.ElencoInterventi.Intervento.IntAnag();
    }

    /**
     * Create an instance of {@link CartellaSociale.BreReport }
     * 
     */
    public CartellaSociale.BreReport createCartellaSocialeBreReport() {
        return new CartellaSociale.BreReport();
    }

    /**
     * Create an instance of {@link CartellaSociale.AnagraficaUtente }
     * 
     */
    public CartellaSociale.AnagraficaUtente createCartellaSocialeAnagraficaUtente() {
        return new CartellaSociale.AnagraficaUtente();
    }

}
