
package it.trieste.comune.cartellasocialews.beans;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0-M2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Cartella", targetNamespace = "http://insiel.it/sanita/cartellasociale/cartellaws/", wsdlLocation = "file:/C:/Users/GOBBOG/git/WelfareGo/cartellasociale-ws/src/main/resources/CartellaSociale.wsdl")
public class Cartella_Service
    extends Service
{

    private final static URL CARTELLA_WSDL_LOCATION;
    private final static WebServiceException CARTELLA_EXCEPTION;
    private final static QName CARTELLA_QNAME = new QName("http://insiel.it/sanita/cartellasociale/cartellaws/", "Cartella");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/GOBBOG/git/WelfareGo/cartellasociale-ws/src/main/resources/CartellaSociale.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARTELLA_WSDL_LOCATION = url;
        CARTELLA_EXCEPTION = e;
    }

    public Cartella_Service() {
        super(__getWsdlLocation(), CARTELLA_QNAME);
    }

    public Cartella_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARTELLA_QNAME, features);
    }

    public Cartella_Service(URL wsdlLocation) {
        super(wsdlLocation, CARTELLA_QNAME);
    }

    public Cartella_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARTELLA_QNAME, features);
    }

    public Cartella_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Cartella_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Cartella
     */
    @WebEndpoint(name = "CartellaSOAP")
    public Cartella getCartellaSOAP() {
        return super.getPort(new QName("http://insiel.it/sanita/cartellasociale/cartellaws/", "CartellaSOAP"), Cartella.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns Cartella
     */
    @WebEndpoint(name = "CartellaSOAP")
    public Cartella getCartellaSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://insiel.it/sanita/cartellasociale/cartellaws/", "CartellaSOAP"), Cartella.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARTELLA_EXCEPTION!= null) {
            throw CARTELLA_EXCEPTION;
        }
        return CARTELLA_WSDL_LOCATION;
    }

}
