ALTER TABLE SOCIALGOTEST.ANAGRAFE_SOC ADD CREATION_USER NUMBER(9,0);
ALTER TABLE SOCIALGOTEST.ANAGRAFE_SOC ADD CREATION_DATE DATE;
ALTER TABLE SOCIALGOTEST.ANAGRAFE_SOC ADD CONSTRAINT ANAGRAFE_SOC_UTENTI_FK FOREIGN KEY (CREATION_USER) REFERENCES SOCIALGOTEST.UTENTI(COD_UTE);